import type { ResourceItem } from "@/lib/content-data";

export const guideSourceResources: ResourceItem[] = [
  {
    id: "guide-source-ipho-through-nstc",
    title: "Guide to IPhO through NSTC",
    subject: "Physics",
    kind: "Guide",
    folder: "Guide Sources",
    year: 2026,
    pages: 0,
    sizeBytes: 0,
    localUrl: null,
    sourceUrl: "https://husky-guan-e1d.notion.site/Guide-to-IPhO-through-NSTC-18754621175380dd8f99f12762588437",
  },
  {
    id: "guide-source-nmtc",
    title: "NMTC Guide",
    subject: "Mathematics",
    kind: "Guide",
    folder: "Guide Sources",
    year: 2026,
    pages: 0,
    sizeBytes: 0,
    localUrl: null,
    sourceUrl: "https://ahmedraza.notion.site/NMTC-Guide-e5f314eb047346bd9f5f78a185793564",
  },
  {
    id: "guide-source-nctc-icho",
    title: "NCTC and IChO Selection Guide",
    subject: "Chemistry",
    kind: "Guide",
    folder: "Guide Sources",
    year: 2026,
    pages: 0,
    sizeBytes: 0,
    localUrl: null,
    sourceUrl: "https://docs.google.com/document/d/1l4rUhUfHuZJftv_2JXVU_hEhO-ZFPPr_j1yWehLLcRk/edit",
  },
  {
    id: "guide-source-poi",
    title: "Pakistan Olympiad in Informatics Guide",
    subject: "Informatics",
    kind: "Guide",
    folder: "Guide Sources",
    year: 2026,
    pages: 0,
    sizeBytes: 0,
    localUrl: null,
    sourceUrl: "https://poi-guide.notion.site/2455dbb3971780fb8547c6bdbc6a9664?v=2455dbb397178065a320000c4d646344",
  },
  {
    id: "guide-source-nbtc",
    title: "NBTC Preparation Guide",
    subject: "Biology",
    kind: "Guide",
    folder: "Guide Sources",
    year: 2026,
    pages: 0,
    sizeBytes: 0,
    localUrl: null,
    sourceUrl: "https://nstcprep.pk/nbtc/guide",
  },
  {
    id: "guide-source-ioaa",
    title: "IOAA Pakistan Guide",
    subject: "Astronomy",
    kind: "Guide",
    folder: "Guide Sources",
    year: 2026,
    pages: 0,
    sizeBytes: 0,
    localUrl: null,
    sourceUrl: "https://husky-guan-e1d.notion.site/IOAA-Pakistan-Guide-21a54621175380bbb45ac694434467b3",
  },
];
