-- Past paper seed
-- Generated by scripts/generate_supabase_seed_sql.ts.
-- Run the schema migration first, then run these seed files in filename order.

begin;

insert into public.past_papers (
  id, status, title, exam, subject, year, pages, resource_url, source_url, scanned,
  page_images, question_count, mcq_count, descriptive_count, part_i_count, part_ii_count, metadata
) values
(
  'biology-2022-final-biology-2022-068e355', 'published', 'NSTC 2022 Biology Paper', 'NSTC', 'Biology',
  2022, 7, '/api/storage/resource-files/past-papers-1/final-biology-2022.pdf',
  'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', false, array['/api/storage/paper-assets/biology-2022-final-biology-2022-068e355/page-1.webp', '/api/storage/paper-assets/biology-2022-final-biology-2022-068e355/page-2.webp', '/api/storage/paper-assets/biology-2022-final-biology-2022-068e355/page-3.webp', '/api/storage/paper-assets/biology-2022-final-biology-2022-068e355/page-4.webp', '/api/storage/paper-assets/biology-2022-final-biology-2022-068e355/page-5.webp', '/api/storage/paper-assets/biology-2022-final-biology-2022-068e355/page-6.webp', '/api/storage/paper-assets/biology-2022-final-biology-2022-068e355/page-7.webp']::text[],
  76, 70, 6,
  20, 50, '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031', 'published', 'NSTC 2022 Chemistry Paper', 'NSTC', 'Chemistry',
  2022, 9, '/api/storage/resource-files/past-papers-1/final-chemistry-2022.pdf',
  'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', false, array['/api/storage/paper-assets/chemistry-2022-final-chemistry-2022-b9f5031/page-1.webp', '/api/storage/paper-assets/chemistry-2022-final-chemistry-2022-b9f5031/page-2.webp', '/api/storage/paper-assets/chemistry-2022-final-chemistry-2022-b9f5031/page-3.webp', '/api/storage/paper-assets/chemistry-2022-final-chemistry-2022-b9f5031/page-4.webp', '/api/storage/paper-assets/chemistry-2022-final-chemistry-2022-b9f5031/page-5.webp', '/api/storage/paper-assets/chemistry-2022-final-chemistry-2022-b9f5031/page-6.webp', '/api/storage/paper-assets/chemistry-2022-final-chemistry-2022-b9f5031/page-7.webp', '/api/storage/paper-assets/chemistry-2022-final-chemistry-2022-b9f5031/page-8.webp', '/api/storage/paper-assets/chemistry-2022-final-chemistry-2022-b9f5031/page-9.webp']::text[],
  71, 70, 1,
  20, 50, '{}'::jsonb
),
(
  'mathematics-2022-final-maths-2022-fb487f9', 'published', 'NSTC 2022 Mathematics Paper', 'NSTC', 'Mathematics',
  2022, 7, '/api/storage/resource-files/past-papers-1/final-maths-2022.pdf',
  'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', false, array['/api/storage/paper-assets/mathematics-2022-final-maths-2022-fb487f9/page-1.webp', '/api/storage/paper-assets/mathematics-2022-final-maths-2022-fb487f9/page-2.webp', '/api/storage/paper-assets/mathematics-2022-final-maths-2022-fb487f9/page-3.webp', '/api/storage/paper-assets/mathematics-2022-final-maths-2022-fb487f9/page-4.webp', '/api/storage/paper-assets/mathematics-2022-final-maths-2022-fb487f9/page-5.webp', '/api/storage/paper-assets/mathematics-2022-final-maths-2022-fb487f9/page-6.webp', '/api/storage/paper-assets/mathematics-2022-final-maths-2022-fb487f9/page-7.webp']::text[],
  72, 70, 2,
  20, 50, '{}'::jsonb
),
(
  'physics-2022-final-physics-2022-b4137e5', 'published', 'NSTC 2022 Physics Paper', 'NSTC', 'Physics',
  2022, 10, '/api/storage/resource-files/past-papers-1/final-physics-2022.pdf',
  'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', false, array['/api/storage/paper-assets/physics-2022-final-physics-2022-b4137e5/page-1.webp', '/api/storage/paper-assets/physics-2022-final-physics-2022-b4137e5/page-2.webp', '/api/storage/paper-assets/physics-2022-final-physics-2022-b4137e5/page-3.webp', '/api/storage/paper-assets/physics-2022-final-physics-2022-b4137e5/page-4.webp', '/api/storage/paper-assets/physics-2022-final-physics-2022-b4137e5/page-5.webp', '/api/storage/paper-assets/physics-2022-final-physics-2022-b4137e5/page-6.webp', '/api/storage/paper-assets/physics-2022-final-physics-2022-b4137e5/page-7.webp', '/api/storage/paper-assets/physics-2022-final-physics-2022-b4137e5/page-8.webp', '/api/storage/paper-assets/physics-2022-final-physics-2022-b4137e5/page-9.webp', '/api/storage/paper-assets/physics-2022-final-physics-2022-b4137e5/page-10.webp']::text[],
  73, 70, 3,
  20, 50, '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6', 'published', 'NSTC 2023 Biology Paper', 'NSTC', 'Biology',
  2023, 6, '/api/storage/resource-files/past-papers-1/final-biology-2023.pdf',
  'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', false, array['/api/storage/paper-assets/biology-2023-final-biology-2023-a4481c6/page-1.webp', '/api/storage/paper-assets/biology-2023-final-biology-2023-a4481c6/page-2.webp', '/api/storage/paper-assets/biology-2023-final-biology-2023-a4481c6/page-3.webp', '/api/storage/paper-assets/biology-2023-final-biology-2023-a4481c6/page-4.webp', '/api/storage/paper-assets/biology-2023-final-biology-2023-a4481c6/page-5.webp', '/api/storage/paper-assets/biology-2023-final-biology-2023-a4481c6/page-6.webp']::text[],
  76, 70, 6,
  20, 50, '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e', 'published', 'NSTC 2023 Chemistry Paper', 'NSTC', 'Chemistry',
  2023, 8, '/api/storage/resource-files/past-papers-1/final-chemistry-2023.pdf',
  'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', false, array['/api/storage/paper-assets/chemistry-2023-final-chemistry-2023-abc462e/page-1.webp', '/api/storage/paper-assets/chemistry-2023-final-chemistry-2023-abc462e/page-2.webp', '/api/storage/paper-assets/chemistry-2023-final-chemistry-2023-abc462e/page-3.webp', '/api/storage/paper-assets/chemistry-2023-final-chemistry-2023-abc462e/page-4.webp', '/api/storage/paper-assets/chemistry-2023-final-chemistry-2023-abc462e/page-5.webp', '/api/storage/paper-assets/chemistry-2023-final-chemistry-2023-abc462e/page-6.webp', '/api/storage/paper-assets/chemistry-2023-final-chemistry-2023-abc462e/page-7.webp', '/api/storage/paper-assets/chemistry-2023-final-chemistry-2023-abc462e/page-8.webp']::text[],
  71, 70, 1,
  20, 50, '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955', 'published', 'NSTC 2023 Mathematics Paper', 'NSTC', 'Mathematics',
  2023, 7, '/api/storage/resource-files/past-papers-1/final-maths-2023.pdf',
  'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', false, array['/api/storage/paper-assets/mathematics-2023-final-maths-2023-4566955/page-1.webp', '/api/storage/paper-assets/mathematics-2023-final-maths-2023-4566955/page-2.webp', '/api/storage/paper-assets/mathematics-2023-final-maths-2023-4566955/page-3.webp', '/api/storage/paper-assets/mathematics-2023-final-maths-2023-4566955/page-4.webp', '/api/storage/paper-assets/mathematics-2023-final-maths-2023-4566955/page-5.webp', '/api/storage/paper-assets/mathematics-2023-final-maths-2023-4566955/page-6.webp', '/api/storage/paper-assets/mathematics-2023-final-maths-2023-4566955/page-7.webp']::text[],
  72, 70, 2,
  20, 50, '{}'::jsonb
),
(
  'physics-2023-final-physics-2023-ac5a924', 'published', 'NSTC 2023 Physics Paper', 'NSTC', 'Physics',
  2023, 9, '/api/storage/resource-files/past-papers-1/final-physics-2023.pdf',
  'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', false, array['/api/storage/paper-assets/physics-2023-final-physics-2023-ac5a924/page-1.webp', '/api/storage/paper-assets/physics-2023-final-physics-2023-ac5a924/page-2.webp', '/api/storage/paper-assets/physics-2023-final-physics-2023-ac5a924/page-3.webp', '/api/storage/paper-assets/physics-2023-final-physics-2023-ac5a924/page-4.webp', '/api/storage/paper-assets/physics-2023-final-physics-2023-ac5a924/page-5.webp', '/api/storage/paper-assets/physics-2023-final-physics-2023-ac5a924/page-6.webp', '/api/storage/paper-assets/physics-2023-final-physics-2023-ac5a924/page-7.webp', '/api/storage/paper-assets/physics-2023-final-physics-2023-ac5a924/page-8.webp', '/api/storage/paper-assets/physics-2023-final-physics-2023-ac5a924/page-9.webp']::text[],
  72, 70, 2,
  20, 50, '{}'::jsonb
),
(
  'biology-2024-final-biology-2024-3efb125', 'published', 'NSTC 2024 Biology Paper', 'NSTC', 'Biology',
  2024, 8, '/api/storage/resource-files/past-papers-1/final-biology-2024.pdf',
  'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', false, array['/api/storage/paper-assets/biology-2024-final-biology-2024-3efb125/page-1.webp', '/api/storage/paper-assets/biology-2024-final-biology-2024-3efb125/page-2.webp', '/api/storage/paper-assets/biology-2024-final-biology-2024-3efb125/page-3.webp', '/api/storage/paper-assets/biology-2024-final-biology-2024-3efb125/page-4.webp', '/api/storage/paper-assets/biology-2024-final-biology-2024-3efb125/page-5.webp', '/api/storage/paper-assets/biology-2024-final-biology-2024-3efb125/page-6.webp', '/api/storage/paper-assets/biology-2024-final-biology-2024-3efb125/page-7.webp', '/api/storage/paper-assets/biology-2024-final-biology-2024-3efb125/page-8.webp']::text[],
  76, 70, 6,
  20, 50, '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740', 'published', 'NSTC 2024 Chemistry Paper', 'NSTC', 'Chemistry',
  2024, 8, '/api/storage/resource-files/past-papers-1/final-chemistry-2024.pdf',
  'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', false, array['/api/storage/paper-assets/chemistry-2024-final-chemistry-2024-1800740/page-1.webp', '/api/storage/paper-assets/chemistry-2024-final-chemistry-2024-1800740/page-2.webp', '/api/storage/paper-assets/chemistry-2024-final-chemistry-2024-1800740/page-3.webp', '/api/storage/paper-assets/chemistry-2024-final-chemistry-2024-1800740/page-4.webp', '/api/storage/paper-assets/chemistry-2024-final-chemistry-2024-1800740/page-5.webp', '/api/storage/paper-assets/chemistry-2024-final-chemistry-2024-1800740/page-6.webp', '/api/storage/paper-assets/chemistry-2024-final-chemistry-2024-1800740/page-7.webp', '/api/storage/paper-assets/chemistry-2024-final-chemistry-2024-1800740/page-8.webp']::text[],
  74, 70, 4,
  20, 50, '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac', 'published', 'NSTC 2024 Mathematics Paper', 'NSTC', 'Mathematics',
  2024, 6, '/api/storage/resource-files/past-papers-1/final-maths-2024.pdf',
  'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', false, array['/api/storage/paper-assets/mathematics-2024-final-maths-2024-640e2ac/page-1.webp', '/api/storage/paper-assets/mathematics-2024-final-maths-2024-640e2ac/page-2.webp', '/api/storage/paper-assets/mathematics-2024-final-maths-2024-640e2ac/page-3.webp', '/api/storage/paper-assets/mathematics-2024-final-maths-2024-640e2ac/page-4.webp', '/api/storage/paper-assets/mathematics-2024-final-maths-2024-640e2ac/page-5.webp', '/api/storage/paper-assets/mathematics-2024-final-maths-2024-640e2ac/page-6.webp']::text[],
  72, 70, 2,
  20, 50, '{}'::jsonb
),
(
  'physics-2024-final-physics-2024-405c90b', 'published', 'NSTC 2024 Physics Paper', 'NSTC', 'Physics',
  2024, 8, '/api/storage/resource-files/past-papers-1/final-physics-2024.pdf',
  'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', false, array['/api/storage/paper-assets/physics-2024-final-physics-2024-405c90b/page-1.webp', '/api/storage/paper-assets/physics-2024-final-physics-2024-405c90b/page-2.webp', '/api/storage/paper-assets/physics-2024-final-physics-2024-405c90b/page-3.webp', '/api/storage/paper-assets/physics-2024-final-physics-2024-405c90b/page-4.webp', '/api/storage/paper-assets/physics-2024-final-physics-2024-405c90b/page-5.webp', '/api/storage/paper-assets/physics-2024-final-physics-2024-405c90b/page-6.webp', '/api/storage/paper-assets/physics-2024-final-physics-2024-405c90b/page-7.webp', '/api/storage/paper-assets/physics-2024-final-physics-2024-405c90b/page-8.webp']::text[],
  72, 70, 2,
  20, 50, '{}'::jsonb
),
(
  'biology-2025-bio-77144bc', 'published', 'NSTC 2025 Biology Paper', 'NSTC', 'Biology',
  2025, 8, '/api/storage/resource-files/past-papers-4/bio.pdf',
  'https://drive.google.com/drive/folders/1T02_pXQ70z14tS6kSMMcXJ1wHttZEKtz?usp=sharing', true, array['/api/storage/paper-assets/biology-2025-bio-77144bc/page-1.webp', '/api/storage/paper-assets/biology-2025-bio-77144bc/page-2.webp', '/api/storage/paper-assets/biology-2025-bio-77144bc/page-3.webp', '/api/storage/paper-assets/biology-2025-bio-77144bc/page-4.webp', '/api/storage/paper-assets/biology-2025-bio-77144bc/page-5.webp', '/api/storage/paper-assets/biology-2025-bio-77144bc/page-6.webp', '/api/storage/paper-assets/biology-2025-bio-77144bc/page-7.webp', '/api/storage/paper-assets/biology-2025-bio-77144bc/page-8.webp']::text[],
  51, 51, 0,
  14, 37, '{}'::jsonb
),
(
  'chemistry-2025-chemistry-7a8e875', 'published', 'NSTC 2025 Chemistry Paper', 'NSTC', 'Chemistry',
  2025, 8, '/api/storage/resource-files/past-papers-4/chemistry.pdf',
  'https://drive.google.com/drive/folders/1T02_pXQ70z14tS6kSMMcXJ1wHttZEKtz?usp=sharing', true, array['/api/storage/paper-assets/chemistry-2025-chemistry-7a8e875/page-1.webp', '/api/storage/paper-assets/chemistry-2025-chemistry-7a8e875/page-2.webp', '/api/storage/paper-assets/chemistry-2025-chemistry-7a8e875/page-3.webp', '/api/storage/paper-assets/chemistry-2025-chemistry-7a8e875/page-4.webp', '/api/storage/paper-assets/chemistry-2025-chemistry-7a8e875/page-5.webp', '/api/storage/paper-assets/chemistry-2025-chemistry-7a8e875/page-6.webp', '/api/storage/paper-assets/chemistry-2025-chemistry-7a8e875/page-7.webp', '/api/storage/paper-assets/chemistry-2025-chemistry-7a8e875/page-8.webp']::text[],
  44, 44, 0,
  19, 25, '{}'::jsonb
),
(
  'mathematics-2025-mathematics-6775970', 'published', 'NSTC 2025 Mathematics Paper', 'NSTC', 'Mathematics',
  2025, 6, '/api/storage/resource-files/past-papers-4/mathematics.pdf',
  'https://drive.google.com/drive/folders/1T02_pXQ70z14tS6kSMMcXJ1wHttZEKtz?usp=sharing', true, array['/api/storage/paper-assets/mathematics-2025-mathematics-6775970/page-1.webp', '/api/storage/paper-assets/mathematics-2025-mathematics-6775970/page-2.webp', '/api/storage/paper-assets/mathematics-2025-mathematics-6775970/page-3.webp', '/api/storage/paper-assets/mathematics-2025-mathematics-6775970/page-4.webp', '/api/storage/paper-assets/mathematics-2025-mathematics-6775970/page-5.webp', '/api/storage/paper-assets/mathematics-2025-mathematics-6775970/page-6.webp']::text[],
  39, 39, 0,
  19, 20, '{}'::jsonb
),
(
  'physics-2025-physics-bf314d9', 'published', 'NSTC 2025 Physics Paper', 'NSTC', 'Physics',
  2025, 9, '/api/storage/resource-files/past-papers-4/physics.pdf',
  'https://drive.google.com/drive/folders/1T02_pXQ70z14tS6kSMMcXJ1wHttZEKtz?usp=sharing', true, array['/api/storage/paper-assets/physics-2025-physics-bf314d9/page-1.webp', '/api/storage/paper-assets/physics-2025-physics-bf314d9/page-2.webp', '/api/storage/paper-assets/physics-2025-physics-bf314d9/page-3.webp', '/api/storage/paper-assets/physics-2025-physics-bf314d9/page-4.webp', '/api/storage/paper-assets/physics-2025-physics-bf314d9/page-5.webp', '/api/storage/paper-assets/physics-2025-physics-bf314d9/page-6.webp', '/api/storage/paper-assets/physics-2025-physics-bf314d9/page-7.webp', '/api/storage/paper-assets/physics-2025-physics-bf314d9/page-8.webp', '/api/storage/paper-assets/physics-2025-physics-bf314d9/page-9.webp']::text[],
  63, 63, 0,
  19, 44, '{}'::jsonb
)
on conflict (id) do update set
  status = excluded.status,
  title = excluded.title,
  exam = excluded.exam,
  subject = excluded.subject,
  year = excluded.year,
  pages = excluded.pages,
  resource_url = excluded.resource_url,
  source_url = excluded.source_url,
  scanned = excluded.scanned,
  page_images = excluded.page_images,
  question_count = excluded.question_count,
  mcq_count = excluded.mcq_count,
  descriptive_count = excluded.descriptive_count,
  part_i_count = excluded.part_i_count,
  part_ii_count = excluded.part_ii_count,
  metadata = excluded.metadata;

commit;
