-- Resource seed
-- Generated by scripts/generate_supabase_seed_sql.ts.
-- Run the schema migration first, then run these seed files in filename order.

begin;

insert into public.resources (
  id, status, title, description, subject, kind, folder, year, pages,
  size_bytes, local_url, source_url, metadata
) values
(
  'ioaa-everaise-astro-book-ed1-protected-unlocked', 'published', 'Everaise Astronomy Handbook, Edition 1', 'Astronomy reference text for building the theory needed before harder olympiad problems.',
  'Astronomy', 'Book', 'ioaa',
  null, 259, 17227899,
  null, 'https://drive.google.com/drive/u/4/folders/127apYXEV79djdzNW1qZeFALBD_1Jo780?usp=sharing', '{}'::jsonb
),
(
  'ioaa-1-fundamentals-of-astronomy-a-guide-for-olympiads', 'published', 'Fundamentals of Astronomy: A Guide for Olympiads', 'Fundamentals of Astronomy: A Guide for Olympiads for planning study order, prerequisites, and preparation strategy.',
  'Astronomy', 'Guide', 'ioaa',
  null, 321, 2741655,
  '/resources/ioaa/1-fundamentals-of-astronomy-a-guide-for-olympiads.pdf', 'https://drive.google.com/drive/u/4/folders/127apYXEV79djdzNW1qZeFALBD_1Jo780?usp=sharing', '{}'::jsonb
),
(
  'ioaa-caao-tutorial', 'published', 'CAAO Tutorial', 'CAAO Tutorial for planning study order, prerequisites, and preparation strategy.',
  'Astronomy', 'Guide', 'ioaa',
  null, 83, 11590775,
  '/resources/ioaa/caao-tutorial.pdf', 'https://drive.google.com/drive/u/4/folders/127apYXEV79djdzNW1qZeFALBD_1Jo780?usp=sharing', '{}'::jsonb
),
(
  'ioaa-ioaa-problems-until-2013-by-topic', 'published', 'IOAA Problems by Topic through 2013', 'Astronomy practice set for focused drills, revision, and timed problem solving.',
  'Astronomy', 'Problem Set', 'ioaa',
  2013, 254, 3889253,
  '/resources/ioaa/ioaa-problems-until-2013-by-topic.pdf', 'https://drive.google.com/drive/u/4/folders/127apYXEV79djdzNW1qZeFALBD_1Jo780?usp=sharing', '{}'::jsonb
),
(
  'ioaa-fundamental-astronomy-6th-ed-2017-edition', 'published', 'Fundamental Astronomy, 6th Edition', 'Astronomy reference file for deeper study, revision, or problem-solving support.',
  'Astronomy', 'Resource', 'ioaa',
  2017, 548, 26700567,
  null, 'https://drive.google.com/drive/u/4/folders/127apYXEV79djdzNW1qZeFALBD_1Jo780?usp=sharing', '{}'::jsonb
),
(
  'ioaa-probability-for-the-enthusiastic-beginner-david-morin-2016-createspace-9781523318674-d34dfadd448fdfcf0fc0e330c43b219d-anna-s-archive', 'published', 'Probability for the Enthusiastic Beginner', 'Astronomy reference file for deeper study, revision, or problem-solving support.',
  'Astronomy', 'Resource', 'ioaa',
  2016, 370, 2286634,
  '/resources/ioaa/probability-for-the-enthusiastic-beginner-david-morin-2016-createspace-9781523318674-d34dfadd448fdfcf0fc0e330c43b219d-anna-s-archive.pdf', 'https://drive.google.com/drive/u/4/folders/127apYXEV79djdzNW1qZeFALBD_1Jo780?usp=sharing', '{}'::jsonb
),
(
  'ioaa-schaum-s-outlines-of-astronomy', 'published', 'Schaum''s Outlines of Astronomy', 'Astronomy reference file for deeper study, revision, or problem-solving support.',
  'Astronomy', 'Resource', 'ioaa',
  null, 241, 4421376,
  '/resources/ioaa/schaum-s-outlines-of-astronomy.pdf', 'https://drive.google.com/drive/u/4/folders/127apYXEV79djdzNW1qZeFALBD_1Jo780?usp=sharing', '{}'::jsonb
),
(
  'ioaa-starmaps101', 'published', 'Star Maps 101', 'Sky-map practice resource for observation, recognition, and orientation work.',
  'Astronomy', 'Resource', 'ioaa',
  null, 121, 51826028,
  null, 'https://drive.google.com/drive/u/4/folders/127apYXEV79djdzNW1qZeFALBD_1Jo780?usp=sharing', '{}'::jsonb
),
(
  'ioaa-taylor-error-analysis', 'published', 'Taylor Error Analysis', 'Error-analysis reference for observational astronomy and experimental uncertainty.',
  'Astronomy', 'Resource', 'ioaa',
  null, 349, 13274683,
  '/resources/ioaa/taylor-error-analysis.pdf', 'https://drive.google.com/drive/u/4/folders/127apYXEV79djdzNW1qZeFALBD_1Jo780?usp=sharing', '{}'::jsonb
),
(
  'biology-01-chapter-evolution', 'published', 'Chapter 1: Evolution', 'Biology reference text for building the theory needed before harder olympiad problems.',
  'Biology', 'Book', 'biology',
  null, 26, 4308738,
  '/resources/biology/01-chapter-evolution.pdf', 'https://drive.google.com/drive/folders/1745To0zPDw1Pb4KiBGzjIZxO0Z7UFzTk', '{}'::jsonb
),
(
  'biology-02-chapter-chemical-context-of-life', 'published', 'Chapter 2: Chemical Context of Life', 'Biology reference text for building the theory needed before harder olympiad problems.',
  'Biology', 'Book', 'biology',
  null, 16, 1914097,
  '/resources/biology/02-chapter-chemical-context-of-life.pdf', 'https://drive.google.com/drive/folders/1745To0zPDw1Pb4KiBGzjIZxO0Z7UFzTk', '{}'::jsonb
),
(
  'biology-03-chapter-water-and-life', 'published', 'Chapter 3: Water and Life', 'Biology reference text for building the theory needed before harder olympiad problems.',
  'Biology', 'Book', 'biology',
  null, 12, 2071237,
  '/resources/biology/03-chapter-water-and-life.pdf', 'https://drive.google.com/drive/folders/1745To0zPDw1Pb4KiBGzjIZxO0Z7UFzTk', '{}'::jsonb
),
(
  'biology-04-chapter-carbon-and-molecular-diversity', 'published', 'Chapter 4: Carbon and Molecular Diversity', 'Biology reference text for building the theory needed before harder olympiad problems.',
  'Biology', 'Book', 'biology',
  null, 10, 1705508,
  '/resources/biology/04-chapter-carbon-and-molecular-diversity.pdf', 'https://drive.google.com/drive/folders/1745To0zPDw1Pb4KiBGzjIZxO0Z7UFzTk', '{}'::jsonb
),
(
  'past-papers-4-bio', 'published', 'NSTC Biology Past Paper 2025', 'Original NSTC biology paper from 2025 for timed practice and review.',
  'Biology', 'Past Paper', 'past-papers-4',
  2025, 8, 2756631,
  '/resources/past-papers-4/bio.pdf', 'https://drive.google.com/drive/folders/1T02_pXQ70z14tS6kSMMcXJ1wHttZEKtz?usp=sharing', '{}'::jsonb
),
(
  'past-papers-1-final-biology-2022', 'published', 'NSTC Biology Past Paper 2022', 'Original NSTC biology paper from 2022 for timed practice and review.',
  'Biology', 'Past Paper', 'past-papers-1',
  2022, 7, 776380,
  '/resources/past-papers-1/final-biology-2022.pdf', 'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', '{}'::jsonb
),
(
  'past-papers-1-final-biology-2023', 'published', 'NSTC Biology Past Paper 2023', 'Original NSTC biology paper from 2023 for timed practice and review.',
  'Biology', 'Past Paper', 'past-papers-1',
  2023, 6, 889734,
  '/resources/past-papers-1/final-biology-2023.pdf', 'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', '{}'::jsonb
),
(
  'past-papers-1-final-biology-2024', 'published', 'NSTC Biology Past Paper 2024', 'Original NSTC biology paper from 2024 for timed practice and review.',
  'Biology', 'Past Paper', 'past-papers-1',
  2024, 8, 695751,
  '/resources/past-papers-1/final-biology-2024.pdf', 'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', '{}'::jsonb
),
(
  'past-papers-4-chemistry', 'published', 'NSTC Chemistry Past Paper 2025', 'Original NSTC chemistry paper from 2025 for timed practice and review.',
  'Chemistry', 'Past Paper', 'past-papers-4',
  2025, 8, 3418977,
  '/resources/past-papers-4/chemistry.pdf', 'https://drive.google.com/drive/folders/1T02_pXQ70z14tS6kSMMcXJ1wHttZEKtz?usp=sharing', '{}'::jsonb
),
(
  'past-papers-1-final-chemistry-2022', 'published', 'NSTC Chemistry Past Paper 2022', 'Original NSTC chemistry paper from 2022 for timed practice and review.',
  'Chemistry', 'Past Paper', 'past-papers-1',
  2022, 9, 849832,
  '/resources/past-papers-1/final-chemistry-2022.pdf', 'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', '{}'::jsonb
),
(
  'past-papers-1-final-chemistry-2023', 'published', 'NSTC Chemistry Past Paper 2023', 'Original NSTC chemistry paper from 2023 for timed practice and review.',
  'Chemistry', 'Past Paper', 'past-papers-1',
  2023, 8, 984660,
  '/resources/past-papers-1/final-chemistry-2023.pdf', 'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', '{}'::jsonb
),
(
  'past-papers-1-final-chemistry-2024', 'published', 'NSTC Chemistry Past Paper 2024', 'Original NSTC chemistry paper from 2024 for timed practice and review.',
  'Chemistry', 'Past Paper', 'past-papers-1',
  2024, 8, 844490,
  '/resources/past-papers-1/final-chemistry-2024.pdf', 'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', '{}'::jsonb
),
(
  'ioaa-a-student-s-guide-to-the-mathematics-of-astronomy', 'published', 'A Student''s Guide to the Mathematics of Astronomy', 'A Student''s Guide to the Mathematics of Astronomy for planning study order, prerequisites, and preparation strategy.',
  'Mathematics', 'Guide', 'ioaa',
  null, 208, 4113967,
  '/resources/ioaa/a-student-s-guide-to-the-mathematics-of-astronomy.pdf', 'https://drive.google.com/drive/u/4/folders/127apYXEV79djdzNW1qZeFALBD_1Jo780?usp=sharing', '{}'::jsonb
),
(
  'past-papers-1-final-maths-2022', 'published', 'NSTC Mathematics Past Paper 2022', 'Original NSTC mathematics paper from 2022 for timed practice and review.',
  'Mathematics', 'Past Paper', 'past-papers-1',
  2022, 7, 1011828,
  '/resources/past-papers-1/final-maths-2022.pdf', 'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', '{}'::jsonb
),
(
  'past-papers-1-final-maths-2023', 'published', 'NSTC Mathematics Past Paper 2023', 'Original NSTC mathematics paper from 2023 for timed practice and review.',
  'Mathematics', 'Past Paper', 'past-papers-1',
  2023, 7, 1039228,
  '/resources/past-papers-1/final-maths-2023.pdf', 'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', '{}'::jsonb
),
(
  'past-papers-1-final-maths-2024', 'published', 'NSTC Mathematics Past Paper 2024', 'Original NSTC mathematics paper from 2024 for timed practice and review.',
  'Mathematics', 'Past Paper', 'past-papers-1',
  2024, 6, 1038803,
  '/resources/past-papers-1/final-maths-2024.pdf', 'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', '{}'::jsonb
),
(
  'past-papers-4-mathematics', 'published', 'NSTC Mathematics Past Paper 2025', 'Original NSTC mathematics paper from 2025 for timed practice and review.',
  'Mathematics', 'Past Paper', 'past-papers-4',
  2025, 6, 2428621,
  '/resources/past-papers-4/mathematics.pdf', 'https://drive.google.com/drive/folders/1T02_pXQ70z14tS6kSMMcXJ1wHttZEKtz?usp=sharing', '{}'::jsonb
),
(
  'math-problem-sets-problem-set-1', 'published', 'Problem Set 1', 'Mathematics practice set for focused drills, revision, and timed problem solving.',
  'Mathematics', 'Problem Set', 'math-problem-sets',
  null, 5, 99608,
  '/resources/math-problem-sets/problem-set-1.pdf', 'https://drive.google.com/drive/folders/15RF3CFO6wea2UIp9vBrmeKWh083cgAep?usp=sharing', '{}'::jsonb
),
(
  'math-problem-sets-problem-set-2', 'published', 'Problem Set 2', 'Mathematics practice set for focused drills, revision, and timed problem solving.',
  'Mathematics', 'Problem Set', 'math-problem-sets',
  null, 5, 99306,
  '/resources/math-problem-sets/problem-set-2.pdf', 'https://drive.google.com/drive/folders/15RF3CFO6wea2UIp9vBrmeKWh083cgAep?usp=sharing', '{}'::jsonb
),
(
  'math-problem-sets-problem-set-3', 'published', 'Problem Set 3', 'Mathematics practice set for focused drills, revision, and timed problem solving.',
  'Mathematics', 'Problem Set', 'math-problem-sets',
  null, 5, 84330,
  '/resources/math-problem-sets/problem-set-3.pdf', 'https://drive.google.com/drive/folders/15RF3CFO6wea2UIp9vBrmeKWh083cgAep?usp=sharing', '{}'::jsonb
),
(
  'math-problem-sets-week-1-algebra', 'published', 'Week 1 Algebra', 'Mathematics practice set for focused drills, revision, and timed problem solving.',
  'Mathematics', 'Problem Set', 'math-problem-sets',
  null, 14, 171424,
  '/resources/math-problem-sets/week-1-algebra.pdf', 'https://drive.google.com/drive/folders/15RF3CFO6wea2UIp9vBrmeKWh083cgAep?usp=sharing', '{}'::jsonb
),
(
  'math-problem-sets-week-2-number-theory', 'published', 'Week 2 Number Theory', 'Mathematics practice set for focused drills, revision, and timed problem solving.',
  'Mathematics', 'Problem Set', 'math-problem-sets',
  null, 15, 215967,
  '/resources/math-problem-sets/week-2-number-theory.pdf', 'https://drive.google.com/drive/folders/15RF3CFO6wea2UIp9vBrmeKWh083cgAep?usp=sharing', '{}'::jsonb
),
(
  'math-problem-sets-week-3-combinatorics', 'published', 'Week 3 Combinatorics', 'Mathematics practice set for focused drills, revision, and timed problem solving.',
  'Mathematics', 'Problem Set', 'math-problem-sets',
  null, 15, 137299,
  '/resources/math-problem-sets/week-3-combinatorics.pdf', 'https://drive.google.com/drive/folders/15RF3CFO6wea2UIp9vBrmeKWh083cgAep?usp=sharing', '{}'::jsonb
),
(
  'math-problem-sets-week-4-geometry', 'published', 'Week 4 Geometry', 'Mathematics practice set for focused drills, revision, and timed problem solving.',
  'Mathematics', 'Problem Set', 'math-problem-sets',
  null, 25, 241834,
  '/resources/math-problem-sets/week-4-geometry.pdf', 'https://drive.google.com/drive/folders/15RF3CFO6wea2UIp9vBrmeKWh083cgAep?usp=sharing', '{}'::jsonb
),
(
  'math-problem-sets-algebra-week-1-solutions', 'published', 'Algebra Week 1 Solutions', 'Worked solution file for checking approaches after attempting the matching problem set.',
  'Mathematics', 'Solution', 'math-problem-sets',
  null, 13, 184409,
  '/resources/math-problem-sets/algebra-week-1-solutions.pdf', 'https://drive.google.com/drive/folders/15RF3CFO6wea2UIp9vBrmeKWh083cgAep?usp=sharing', '{}'::jsonb
),
(
  'math-problem-sets-pset-1-solutions', 'published', 'Problem Set 1 Solutions', 'Worked solution file for checking approaches after attempting the matching problem set.',
  'Mathematics', 'Solution', 'math-problem-sets',
  null, 11, 166121,
  '/resources/math-problem-sets/pset-1-solutions.pdf', 'https://drive.google.com/drive/folders/15RF3CFO6wea2UIp9vBrmeKWh083cgAep?usp=sharing', '{}'::jsonb
),
(
  'math-problem-sets-pset-2-solutions', 'published', 'Problem Set 2 Solutions', 'Worked solution file for checking approaches after attempting the matching problem set.',
  'Mathematics', 'Solution', 'math-problem-sets',
  null, 13, 168687,
  '/resources/math-problem-sets/pset-2-solutions.pdf', 'https://drive.google.com/drive/folders/15RF3CFO6wea2UIp9vBrmeKWh083cgAep?usp=sharing', '{}'::jsonb
),
(
  'math-problem-sets-pset-3-solutions', 'published', 'Problem Set 3 Solutions', 'Worked solution file for checking approaches after attempting the matching problem set.',
  'Mathematics', 'Solution', 'math-problem-sets',
  null, 9, 133168,
  '/resources/math-problem-sets/pset-3-solutions.pdf', 'https://drive.google.com/drive/folders/15RF3CFO6wea2UIp9vBrmeKWh083cgAep?usp=sharing', '{}'::jsonb
),
(
  'physics-1-physics-10', 'published', 'Physics 10', 'Physics reference text for building the theory needed before harder olympiad problems.',
  'Physics', 'Book', 'physics-1',
  null, 201, 31106151,
  null, 'https://drive.google.com/drive/u/4/folders/10h6RwSopzdbV2UviovnaimqmlgZ9SJNc', '{}'::jsonb
),
(
  'physics-1-physics-9', 'published', 'Physics 9', 'Physics reference text for building the theory needed before harder olympiad problems.',
  'Physics', 'Book', 'physics-1',
  null, 208, 37268953,
  null, 'https://drive.google.com/drive/u/4/folders/10h6RwSopzdbV2UviovnaimqmlgZ9SJNc', '{}'::jsonb
),
(
  'physics-1-physicsbook1', 'published', 'Physicsbook1', 'Physics reference text for building the theory needed before harder olympiad problems.',
  'Physics', 'Book', 'physics-1',
  null, 285, 53348708,
  null, 'https://drive.google.com/drive/u/4/folders/10h6RwSopzdbV2UviovnaimqmlgZ9SJNc', '{}'::jsonb
),
(
  'past-papers-1-final-physics-2022', 'published', 'NSTC Physics Past Paper 2022', 'Original NSTC physics paper from 2022 for timed practice and review.',
  'Physics', 'Past Paper', 'past-papers-1',
  2022, 10, 1086867,
  '/resources/past-papers-1/final-physics-2022.pdf', 'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', '{}'::jsonb
),
(
  'past-papers-1-final-physics-2023', 'published', 'NSTC Physics Past Paper 2023', 'Original NSTC physics paper from 2023 for timed practice and review.',
  'Physics', 'Past Paper', 'past-papers-1',
  2023, 9, 983795,
  '/resources/past-papers-1/final-physics-2023.pdf', 'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', '{}'::jsonb
),
(
  'past-papers-1-final-physics-2024', 'published', 'NSTC Physics Past Paper 2024', 'Original NSTC physics paper from 2024 for timed practice and review.',
  'Physics', 'Past Paper', 'past-papers-1',
  2024, 8, 929796,
  '/resources/past-papers-1/final-physics-2024.pdf', 'https://drive.google.com/drive/folders/1t-bQK0E98jY05WUnChDpNrQViLCCyl7y?usp=sharing', '{}'::jsonb
),
(
  'past-papers-4-physics', 'published', 'NSTC Physics Past Paper 2025', 'Original NSTC physics paper from 2025 for timed practice and review.',
  'Physics', 'Past Paper', 'past-papers-4',
  2025, 9, 3616348,
  '/resources/past-papers-4/physics.pdf', 'https://drive.google.com/drive/folders/1T02_pXQ70z14tS6kSMMcXJ1wHttZEKtz?usp=sharing', '{}'::jsonb
),
(
  'physics-2-calculus-day-1-problems', 'published', 'Calculus Day 1 Problems', 'Physics practice set for focused drills, revision, and timed problem solving.',
  'Physics', 'Problem Set', 'physics-2',
  null, 8, 63760,
  '/resources/physics-2/calculus-day-1-problems.pdf', 'https://drive.google.com/drive/folders/1SiPFWQfwrTkBIA6WmE6Mua9g3SDoJ1nV', '{}'::jsonb
),
(
  'physics-2-calculus-day-2-problems', 'published', 'Calculus Day 2 Problems', 'Physics practice set for focused drills, revision, and timed problem solving.',
  'Physics', 'Problem Set', 'physics-2',
  null, 4, 116056,
  '/resources/physics-2/calculus-day-2-problems.pdf', 'https://drive.google.com/drive/folders/1SiPFWQfwrTkBIA6WmE6Mua9g3SDoJ1nV', '{}'::jsonb
),
(
  'physics-2-calculus-day-3-problems', 'published', 'Calculus Day 3 Problems', 'Physics practice set for focused drills, revision, and timed problem solving.',
  'Physics', 'Problem Set', 'physics-2',
  null, 4, 135115,
  '/resources/physics-2/calculus-day-3-problems.pdf', 'https://drive.google.com/drive/folders/1SiPFWQfwrTkBIA6WmE6Mua9g3SDoJ1nV', '{}'::jsonb
),
(
  'physics-2-calculus-day-4-problems', 'published', 'Calculus Day 4 Problems', 'Physics practice set for focused drills, revision, and timed problem solving.',
  'Physics', 'Problem Set', 'physics-2',
  null, 7, 150628,
  '/resources/physics-2/calculus-day-4-problems.pdf', 'https://drive.google.com/drive/folders/1SiPFWQfwrTkBIA6WmE6Mua9g3SDoJ1nV', '{}'::jsonb
),
(
  'physics-2-calculus-mechanics-problems', 'published', 'Calculus Mechanics Problems', 'Physics practice set for focused drills, revision, and timed problem solving.',
  'Physics', 'Problem Set', 'physics-2',
  null, 6, 76983,
  '/resources/physics-2/calculus-mechanics-problems.pdf', 'https://drive.google.com/drive/folders/1SiPFWQfwrTkBIA6WmE6Mua9g3SDoJ1nV', '{}'::jsonb
),
(
  'physics-2-calculus-day-1', 'published', 'Calculus Day 1', 'Physics reference file for deeper study, revision, or problem-solving support.',
  'Physics', 'Resource', 'physics-2',
  null, 7, 156836,
  '/resources/physics-2/calculus-day-1.pdf', 'https://drive.google.com/drive/folders/1SiPFWQfwrTkBIA6WmE6Mua9g3SDoJ1nV', '{}'::jsonb
),
(
  'physics-2-calculus-day-2', 'published', 'Calculus Day 2', 'Physics reference file for deeper study, revision, or problem-solving support.',
  'Physics', 'Resource', 'physics-2',
  null, 23, 181972,
  '/resources/physics-2/calculus-day-2.pdf', 'https://drive.google.com/drive/folders/1SiPFWQfwrTkBIA6WmE6Mua9g3SDoJ1nV', '{}'::jsonb
),
(
  'physics-2-calculus-day-3', 'published', 'Calculus Day 3', 'Physics reference file for deeper study, revision, or problem-solving support.',
  'Physics', 'Resource', 'physics-2',
  null, 14, 183144,
  '/resources/physics-2/calculus-day-3.pdf', 'https://drive.google.com/drive/folders/1SiPFWQfwrTkBIA6WmE6Mua9g3SDoJ1nV', '{}'::jsonb
),
(
  'physics-2-calculus-day-4', 'published', 'Calculus Day 4', 'Physics reference file for deeper study, revision, or problem-solving support.',
  'Physics', 'Resource', 'physics-2',
  null, 14, 715041,
  '/resources/physics-2/calculus-day-4.pdf', 'https://drive.google.com/drive/folders/1SiPFWQfwrTkBIA6WmE6Mua9g3SDoJ1nV', '{}'::jsonb
),
(
  'physics-1-hrk-physics-2', 'published', 'Hrk Physics 2', 'Physics reference file for deeper study, revision, or problem-solving support.',
  'Physics', 'Resource', 'physics-1',
  null, 695, 436527923,
  null, 'https://drive.google.com/drive/u/4/folders/10h6RwSopzdbV2UviovnaimqmlgZ9SJNc', '{}'::jsonb
),
(
  'guide-source-ipho-through-nstc', 'published', 'Guide to Ipho Through Nstc', 'Original IPhO guide source retained for attribution and cross-checking.',
  'Physics', 'Guide', 'Guide Sources',
  2026, 0, 0,
  null, 'https://husky-guan-e1d.notion.site/Guide-to-IPhO-through-NSTC-18754621175380dd8f99f12762588437', '{}'::jsonb
),
(
  'guide-source-nmtc', 'published', 'Nmtc Guide', 'Original mathematics guide source retained for attribution and cross-checking.',
  'Mathematics', 'Guide', 'Guide Sources',
  2026, 0, 0,
  null, 'https://ahmedraza.notion.site/NMTC-Guide-e5f314eb047346bd9f5f78a185793564', '{}'::jsonb
),
(
  'guide-source-nctc-icho', 'published', 'Nctc and Icho Selection Guide', 'Original chemistry guide source retained for attribution and cross-checking.',
  'Chemistry', 'Guide', 'Guide Sources',
  2026, 0, 0,
  null, 'https://docs.google.com/document/d/1l4rUhUfHuZJftv_2JXVU_hEhO-ZFPPr_j1yWehLLcRk/edit', '{}'::jsonb
),
(
  'guide-source-poi', 'published', 'Pakistan Olympiad in Informatics Guide', 'Original informatics guide source retained for attribution and cross-checking.',
  'Informatics', 'Guide', 'Guide Sources',
  2026, 0, 0,
  null, 'https://poi-guide.notion.site/2455dbb3971780fb8547c6bdbc6a9664?v=2455dbb397178065a320000c4d646344', '{}'::jsonb
),
(
  'guide-source-nbtc', 'published', 'Nbtc Preparation Guide', 'Original biology guide source retained for attribution and cross-checking.',
  'Biology', 'Guide', 'Guide Sources',
  2026, 0, 0,
  null, 'https://nstcprep.pk/nbtc/guide', '{}'::jsonb
),
(
  'guide-source-ioaa', 'published', 'Ioaa Pakistan Guide', 'Original astronomy guide source retained for attribution and cross-checking.',
  'Astronomy', 'Guide', 'Guide Sources',
  2026, 0, 0,
  null, 'https://husky-guan-e1d.notion.site/IOAA-Pakistan-Guide-21a54621175380bbb45ac694434467b3', '{}'::jsonb
)
on conflict (id) do update set
  status = excluded.status,
  title = excluded.title,
  description = excluded.description,
  subject = excluded.subject,
  kind = excluded.kind,
  folder = excluded.folder,
  year = excluded.year,
  pages = excluded.pages,
  size_bytes = excluded.size_bytes,
  local_url = excluded.local_url,
  source_url = excluded.source_url,
  metadata = excluded.metadata;

commit;
