-- Question seed chunk 5
-- Generated by scripts/generate_supabase_seed_sql.ts.
-- Run the schema migration first, then run these seed files in filename order.

begin;

insert into public.questions (
  id, status, paper_id, paper_subject, number, display_number, subject, topic,
  difficulty, type, section, section_title, exam, year, source, prompt,
  options, answer, solution, page, figure, metadata
) values
(
  'mathematics-2022-final-maths-2022-fb487f9-part-ii-62', 'published', 'mathematics-2022-final-maths-2022-fb487f9', 'Mathematics',
  62, '62', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2022, 'NSTC 2022 Mathematics Paper', 'The solution of 2x−9 ≥ 7 is',
  '["[8, ∞)","(−∞, ∞)","(8, ∞)","(−∞, 8)"]'::jsonb, 0, 'Correct option: A. [8, ∞) is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2022-final-maths-2022-fb487f9-part-ii-63', 'published', 'mathematics-2022-final-maths-2022-fb487f9', 'Mathematics',
  63, '63', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2022, 'NSTC 2022 Mathematics Paper', 'The inverse of the function f (x) = 2x−9 is',
  '["(x+9)/2","(x-9)/2","(x+2)/9","(x-2)/"]'::jsonb, 0, 'Correct option: A. (x+9)/2 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2022-final-maths-2022-fb487f9-part-ii-64', 'published', 'mathematics-2022-final-maths-2022-fb487f9', 'Mathematics',
  64, '64', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2022, 'NSTC 2022 Mathematics Paper', 'Polygon with 9 sides is called',
  '["heptagon","nanogon","octagon","pentagon"]'::jsonb, 1, 'Correct option: B. nanogon is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2022-final-maths-2022-fb487f9-part-ii-65', 'published', 'mathematics-2022-final-maths-2022-fb487f9', 'Mathematics',
  65, '65', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2022, 'NSTC 2022 Mathematics Paper', 'Area of a rhombus having diagonals equal to 6 cm and 8 cm is',
  '["48 cm2","36 cm2","24 cm2","64 cm2"]'::jsonb, 2, 'Correct option: C. 24 cm2 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2022-final-maths-2022-fb487f9-part-ii-66', 'published', 'mathematics-2022-final-maths-2022-fb487f9', 'Mathematics',
  66, '66', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2022, 'NSTC 2022 Mathematics Paper', 'The length of a rectangular screen is 15 cm. Its area is 180 sq. cm. Its width is',
  '["18 cm","12 cm","10 cm","15 cm"]'::jsonb, 1, 'Correct option: B. 12 cm is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2022-final-maths-2022-fb487f9-part-ii-67', 'published', 'mathematics-2022-final-maths-2022-fb487f9', 'Mathematics',
  67, '67', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2022, 'NSTC 2022 Mathematics Paper', 'If f (x−3) = 9x2+2 then f (5) is',
  '["578","227","555","None of these"]'::jsonb, 0, 'Correct option: A. 578 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'mathematics-2022-final-maths-2022-fb487f9-part-ii-68', 'published', 'mathematics-2022-final-maths-2022-fb487f9', 'Mathematics',
  68, '68', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2022, 'NSTC 2022 Mathematics Paper', 'The expression √20 − √20 − √20 − √20 − ⋯ is equal to',
  '["20","5","4","None of these"]'::jsonb, 2, 'Correct option: C. 4 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'mathematics-2022-final-maths-2022-fb487f9-part-ii-69', 'published', 'mathematics-2022-final-maths-2022-fb487f9', 'Mathematics',
  69, '69', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2022, 'NSTC 2022 Mathematics Paper', 'The value of cos(tan−1(−1)) is',
  '["1 2","− 1 √2","−𝜋","√"]'::jsonb, 3, 'Correct option: D. √ is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'mathematics-2022-final-maths-2022-fb487f9-part-ii-70', 'published', 'mathematics-2022-final-maths-2022-fb487f9', 'Mathematics',
  70, '70', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2022, 'NSTC 2022 Mathematics Paper', 'A pair of chords of a circle subtending two congruent central angles is',
  '["parallel","congruent","over lapping","incongruent"]'::jsonb, 1, 'Correct option: B. congruent is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'mathematics-2022-final-maths-2022-fb487f9-part-iii-1', 'published', 'mathematics-2022-final-maths-2022-fb487f9', 'Mathematics',
  1, 'Descriptive 1', 'Mathematics',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2022, 'NSTC 2022 Mathematics Paper', 'Question No 1: Find value of √2 √2 √2 √2 √2 … − √2 + √2 + √2 + √2 + √2 + ⋯',
  '[]'::jsonb, null, 'Let x=sqrt(2x) for the nested product radical; the positive solution is x=2. Let y=sqrt(2+y) for the nested sum radical; y^2=2+y gives y=2. Therefore the required difference is 2-2=0.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2022-final-maths-2022-fb487f9-part-iii-2', 'published', 'mathematics-2022-final-maths-2022-fb487f9', 'Mathematics',
  2, 'Descriptive 2', 'Mathematics',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2022, 'NSTC 2022 Mathematics Paper', 'Question No 2: Given BE and CF are the altitudes of the triangle ABC. P, Q are on BE and the extension of CF respectively such that BP = AC, CQ = AB. Prove that AP and AQ perpendicular. --',
  '[]'::jsonb, null, 'Use vectors from A. Since BP is perpendicular to AC and |BP|=|AC|, vector AP equals vector AB plus a right-angle rotation of vector AC. Similarly, because CQ is perpendicular to AB and |CQ|=|AB|, vector AQ equals vector AC minus the same right-angle rotation of vector AB. Their dot product is AB dot AC minus AB dot AC, which is 0; hence AP is perpendicular to AQ.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-1', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  1, '1', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'During cellular respiration breakdown of glucose occurs in',
  '["Vacuole","Golgi complex","Mitochondria","Cytoplasm"]'::jsonb, 2, 'Most aerobic breakdown of glucose occurs in mitochondria.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-2', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  2, '2', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'The hypothesis that stands the test of time are called',
  '["Law","Null hypothesis","Principle","Theories"]'::jsonb, 3, 'Hypotheses that remain supported by repeated testing are called theories.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-3', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  3, '3', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Cancer is disease of',
  '["Simple cell division","Uncontrolled cell division","Controlled cell division","Accelerated cell division"]'::jsonb, 1, 'Cancer is characterized by uncontrolled cell division.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-4', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  4, '4', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'A conjugate acid is a specie formed by accepting a',
  '["Electron pair","Neutron","Proton","Electron"]'::jsonb, 2, 'A conjugate acid forms when a base accepts a proton.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-5', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  5, '5', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'In which phase of Meiosis the homologous chromosomes separated from each other',
  '["prophase 1","telophase 1","anaphase 1","metaphase 1"]'::jsonb, 2, 'Homologous chromosomes separate during anaphase I of meiosis.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-6', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  6, '6', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'All of the following substance are crystalline except',
  '["Ice","Diamond","Sucrose","Plastic"]'::jsonb, 3, 'Plastic is generally amorphous rather than crystalline.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-7', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  7, '7', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Diameter of an atom in the order of',
  '["0.2μm","0.2mm","0.2nm","0.2pm"]'::jsonb, 2, 'Atomic diameters are on the order of 10^-10 m, or about 0.2 nm.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-8', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  8, '8', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Which of the following is not a macromolecule',
  '["Sand","Hemoglobin","Diamond","Maltose"]'::jsonb, 3, 'Maltose is a small disaccharide, not a macromolecule.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-9', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  9, '9', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'About how many elements in the Periodic Table are Metals',
  '["60%","65%","70%","75%"]'::jsonb, 3, 'Most periodic-table elements are metals; 75 percent is the closest listed value.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-10', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  10, '10', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Plasma is used in',
  '["Florescent bulb","Neon signs","Laser","All of these"]'::jsonb, 3, 'Plasmas are used in fluorescent lamps, neon signs, and some laser systems.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-11', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  11, '11', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'The distance between the points (-2, 2) and (1, 6) is',
  '["25 units","5 units","7 units","none of these"]'::jsonb, 1, 'The distance is sqrt((1+2)^2+(6-2)^2)=sqrt(25)=5.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-12', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  12, '12', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Angles that sum up to 90 ° are known as',
  '["complementary angles","vertical angles","reflective angles","supplementary angles"]'::jsonb, 0, 'Angles whose measures add to 90 degrees are complementary.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-13', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  13, '13', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Total number of lines passing through the point (0,0) are',
  '["0","1","2","infinity"]'::jsonb, 3, 'Infinitely many lines can pass through a single point in a plane.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-14', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  14, '14', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'The coordinates of the midpoint of points in plane with coordinates (−2,8) and (8, −2) is',
  '["(0,0)","(3,3)","(2,2)","(8,8)"]'::jsonb, 1, 'The midpoint is ((-2+8)/2,(8-2)/2)=(3,3).',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-15', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  15, '15', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'If 𝑥 + 1 𝑥 = 2, then the value of 𝑥2 + 1 𝑥2 is',
  '["1/4","1","3","2"]'::jsonb, 3, 'If x+1/x=2, then x^2+1/x^2=(x+1/x)^2-2=2.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-16', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  16, '16', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'A net force of 10. Newtons accelerates an object at 5.0 m/s 2. What net force would be required to accelerate the same object at 1.0 m/s2?',
  '["1.0 N","2.0 N","5 N","10 N"]'::jsonb, 1, 'The mass is F/a=10/5=2 kg, so a 1.0 m/s^2 acceleration needs 2.0 N.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-17', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  17, '17', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'A 1,200-kilogram car traveling at 10. m/s hits a tree and is brought to rest in 0.10 second. What is the magnitude of the average force acting on the car to bring it to rest?',
  '["1.2 x 10^2 N","1.2 x 10^3 N","1.2 x 10^4 N","1.2 x 10^5 N"]'::jsonb, 3, 'Average force is change in momentum over time: (1200 kg)(10 m/s)/0.10 s=1.2 x 10^5 N.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-18', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  18, '18', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'When a neutral metal sphere is charged by contact with a positively charged glass rod, the sphere',
  '["loses electrons","loses protons","gains electrons","gains protons"]'::jsonb, 0, 'A positively charged rod removes electrons from the neutral metal during contact.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-19', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  19, '19', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'An electric iron operating at 120 volts draws 10. Amperes of current. How much heat energy is delivered by the iron in 30 Seconds?',
  '["3.0 x 10^2 J","3.6 x 10^3 J","1.2 x 10^3 J","3.6 x 10^4 J"]'::jsonb, 3, 'Heat delivered is VIt=(120 V)(10 A)(30 s)=3.6 x 10^4 J.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-i-20', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  20, '20', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'A radar gun can determine the speed of a moving automobile by measuring the difference infrequency between emitted and reflected radar waves. This process illustrates',
  '["resonance","diffraction","the Doppler effect","refraction"]'::jsonb, 2, 'Speed measurement from a frequency shift of reflected waves uses the Doppler effect.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-21', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  21, '21', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'A chord of length 24cm is at a distance of 5cm from the center of a circle. The radius of the circle is',
  '["13 𝑐𝑚","19 𝑐𝑚","12 𝑐𝑚","5 𝑐𝑚"]'::jsonb, 0, 'Correct option: A. 13 𝑐𝑚 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-22', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  22, '22', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Find the slope of the line with equation 3 2 10xy+=',
  '["10","3/ 2-","3/ 2","None of these"]'::jsonb, 1, 'Correct option: B. 3/ 2- is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-23', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  23, '23', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Consider a triangle 𝐴𝐵𝐶 with ∠𝐵 = 30° and ∠𝐶 = 60°. What is the type of ∆𝐴𝐵𝐶?',
  '["Right Angle","Isosceles","Acute","Obtuse"]'::jsonb, 0, 'Correct option: A. Right Angle is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-24', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  24, '24', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Total number of circles that can pass through 2 pair of points in a plane are',
  '["0","1","2","infinity"]'::jsonb, 3, 'Correct option: D. infinity is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-25', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  25, '25', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Length of a diagonal of a rectangle with length 4 𝑐𝑚 and width 3 𝑐𝑚 is',
  '["√7 𝑐𝑚","5 𝑐𝑚","4 𝑐𝑚","3 𝑐𝑚"]'::jsonb, 1, 'Correct option: B. 5 𝑐𝑚 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-26', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  26, '26', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Surface Area of a sphere with radius 3𝑐𝑚 is',
  '["36π 𝑐𝑚3","36π 𝑐𝑚2","9π 𝑐𝑚2","18π 𝑐𝑚 2"]'::jsonb, 1, 'Correct option: B. 36π 𝑐𝑚2 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-27', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  27, '27', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'In a right angle triangle length of the hypotenuse is 5cm and length of one side is 4cm. What is the perimeter of the triangle?',
  '["6 𝑐𝑚","8 𝑐𝑚","12𝑐𝑚","None of these"]'::jsonb, 2, 'Correct option: C. 12𝑐𝑚 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-28', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  28, '28', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'How many minimum points are required to draw a unique line in a plane',
  '["1 point","2 points","3 points","None of these"]'::jsonb, 1, 'Correct option: B. 2 points is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-29', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  29, '29', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'If the supplement of an angle is 3 times of its compliment, find the angle.',
  '["90°","60°","45°","30°"]'::jsonb, 2, 'Correct option: C. 45° is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-30', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  30, '30', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Maximum number of intersection points of 5 non parallel distinct lines in a plane are',
  '["5","10","15","20"]'::jsonb, 1, 'Correct option: B. 10 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-31', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  31, '31', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'The distance between two parallel tangents of a circle of radius 6 cm is',
  '["3 cm","6 cm","12 cm","15 cm"]'::jsonb, 2, 'Correct option: C. 12 cm is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-32', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  32, '32', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'The ratio of heights of a cone and a hemisphere with equal bases and equal volumes is',
  '["1 ∶ 1","1 ∶ 2","2 ∶ 1","None of these"]'::jsonb, 2, 'Correct option: C. 2 ∶ 1 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-33', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  33, '33', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'If 𝑥2 + 𝑦2 + 𝑧2 = 125 and 𝑥𝑦 + 𝑦𝑧 + 𝑧𝑎 = 250, then 𝑥 + 𝑦 + 𝑧 is',
  '["25","35","45","55"]'::jsonb, 0, 'Correct option: A. 25 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-34', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  34, '34', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'The quadratic equation corresponding to the roots 2 + √5 and 2 − √5 is',
  '["𝑥2 − 4𝑥 − 1 = 0","𝑥2 + 4𝑥 + 1 = 0","𝑥2 − 4𝑥 + 1 = 0","𝑥 2 + 4𝑥 + 1 = 0"]'::jsonb, 0, 'Correct option: A. 𝑥2 − 4𝑥 − 1 = 0 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-35', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  35, '35', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'The function 𝑓: 𝑅 → 𝑅 defined by 𝑓(𝑥) = 2𝑥2 + 𝑥 − 1 is',
  '["only onto","only one-one","both one-one and onto","neither one- one nor onto"]'::jsonb, 3, 'Correct option: D. neither one- one nor onto is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-36', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  36, '36', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'The number of real solutions of the equation 𝑥4 − 1 = 0 are',
  '["0","1","2","4"]'::jsonb, 2, 'Correct option: C. 2 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-37', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  37, '37', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'If 𝑥2 − 4𝑥 + 4 = 0, then the value of 𝑥2 is',
  '["0","2","4","16"]'::jsonb, 2, 'Correct option: C. 4 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-38', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  38, '38', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Which of the following is not irrational?',
  '["2(2 − 3√3)","2(√2 + √3)","(√2 − √3)(√2 + √3)","2√7/ 7"]'::jsonb, 2, 'Correct option: C. (√2 − √3)(√2 + √3) is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-39', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  39, '39', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'If 𝑑|𝑎 and 𝑑|𝑏, then',
  '["𝑑|𝑎𝑏","𝑑|𝑏𝑎","𝑑|(𝑎 − 𝑏)","None"]'::jsonb, 2, 'Correct option: C. 𝑑|(𝑎 − 𝑏) is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-40', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  40, '40', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Positive divisor of both 𝑎 and 𝑎 + 1 is',
  '["𝑎","𝑎 − 1","1","All"]'::jsonb, 2, 'Correct option: C. 1 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-41', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  41, '41', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', '−123 ≡ 𝑎(mod 10)',
  '["3","1","5","7"]'::jsonb, 3, 'Correct option: D. 7 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-42', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  42, '42', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'gcd(2𝑎 + 1,9𝑎 + 4) =',
  '["𝑎","2𝑎","𝑎 + 1","1"]'::jsonb, 3, 'Correct option: D. 1 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-43', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  43, '43', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'If 𝑝 is prime and 𝑝|𝑎𝑛, then',
  '["𝑝|𝑎𝑛-1","𝑝𝑛|𝑎𝑛","𝑎|𝑝","all"]'::jsonb, 1, 'Correct option: B. 𝑝𝑛|𝑎𝑛 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-44', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  44, '44', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'The remainders when 250 is divided by 7.',
  '["4","6","2","1"]'::jsonb, 0, 'Correct option: A. 4 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-45', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  45, '45', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'A girl wrote all the numbers from 100 to 200. Then she started counting the number of one''s that has been used while writing all these numbers. What is the number that she got?',
  '["111","119","120","121"]'::jsonb, 2, 'Correct option: C. 120 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-46', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  46, '46', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'If each of the three nonzero numbers 𝑎, 𝑏 and 𝑐 is divisible by 3, then 𝑎𝑏𝑐 must be divisible by which one of the following the numbers?',
  '["8","27","81","121"]'::jsonb, 1, 'Correct option: B. 27 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-47', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  47, '47', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'If n is a positive integer, which one of the following numbers must have a remainder of 3 when divided by any of the numbers 4, 5 and 6?',
  '["12n+3","24n+3","90n+2","120n+3"]'::jsonb, 3, 'Correct option: D. 120n+3 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-48', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  48, '48', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'When a particular positive number is divided by 5, the remainder is 2. If the same number is divided by 6, the remainder is 1. If the difference between the quotients of division is 3, then find the number.',
  '["37","97","67","87"]'::jsonb, 1, 'Correct option: B. 97 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-49', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  49, '49', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'A certain number when divided by 222 leaves a remainder 35, another number when divided by 407 leaves a remainder 47. What is the remainder when the sum of these two numbers is divided by 37?',
  '["8","9","12","17"]'::jsonb, 0, 'Correct option: A. 8 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-50', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  50, '50', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'The number obtained by interchanging the two digits of a two digit number is less than the original number by 27. If the difference between the two digits of the number is 3, what is the original number?',
  '["74","63","85","Cannot be determined"]'::jsonb, 3, 'Correct option: D. Cannot be determined is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-51', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  51, '51', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'A six-person committee composed of Alice, Ben, Connie, Dolph, Egbert, and Francisco is to select a chairperson, secretary, and treasurer. In how many ways can this be done if either Alice or Ben must be chairperson?',
  '["20","120","60","40"]'::jsonb, 3, 'Correct option: D. 40 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-52', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  52, '52', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'A boy lives at X and wants to go to School at Z. From his home X he has to first reach Y and then Y to Z. He may go X to Y by either 3 bus routes or 2 train routes. From there, he can either choose 4 bus routes or 5 train routes to reach Z. How many ways are there to go from X to Z?',
  '["5","9","45","14"]'::jsonb, 2, 'Correct option: C. 45 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-53', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  53, '53', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'In a group of 50 students 24 like cold drinks and 36 like hot drinks and each student likes at least one of the two drinks. How many like both coffee and tea?',
  '["10","20","30","40"]'::jsonb, 0, 'Correct option: A. 10 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-54', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  54, '54', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'In an arithmetic progression the 𝑚 times of 𝑚𝑡ℎ term is equal to 𝑛 times the 𝑛𝑡ℎ term, its (𝑚 + 𝑛)𝑡ℎ term will be',
  '["0","𝑚𝑛","𝑚 + 𝑛 𝑚𝑛","1 + 𝑚 + 𝑛"]'::jsonb, 0, 'Correct option: A. 0 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-55', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  55, '55', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'In the expansion of (2𝑎 − 3𝑏)6, determine the coefficient of the term containing 𝑎4𝑏2.',
  '["−4320","864","2160","2880"]'::jsonb, 2, 'Correct option: C. 2160 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-56', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  56, '56', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'In a colony, there are 55 members. Every member posts a greeting card to all the members. How many greeting cards were posted by them?',
  '["990","890","2970","1980"]'::jsonb, 2, 'Correct option: C. 2970 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-57', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  57, '57', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'There are 20 points in a plane, how many triangles can be formed by these points if 5 are collinear?',
  '["1130","550","1129","1140"]'::jsonb, 0, 'Correct option: A. 1130 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-58', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  58, '58', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'How many odd 3-digit whole numbers are there? For example, 203 is acceptable but 023 is not.',
  '["360","450","500","900"]'::jsonb, 1, 'Correct option: B. 450 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-59', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  59, '59', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Consider the recurrence relation 𝑎𝑛 = 𝑎𝑛−1 + 𝑛 with initial condition 𝑎1 = 1. The value of 𝑎13 is __________',
  '["91","101","85","113"]'::jsonb, 0, 'Correct option: A. 91 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-60', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  60, '60', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'How many numbers must be selected from the set {1, 2, 3, 4, 5, 6} to guarantee that at least one pair of these numbers add up to 7?',
  '["1","4","3","2"]'::jsonb, 1, 'Correct option: B. 4 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-61', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  61, '61', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'If arithmetic mean of 6, 7, 9, 𝑥 is 10, then value of 𝑥 is',
  '["20","22","18","24"]'::jsonb, 2, 'Correct option: C. 18 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-62', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  62, '62', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Find the number of ways of arranging the letters of the words DANGER, so that no vowel occupies odd place.',
  '["36","48","144","96"]'::jsonb, 2, 'Correct option: C. 144 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-63', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  63, '63', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'If nPr = 3024 and nCr = 126 then find n and r.',
  '["9, 4","10, 3","12, 4","11, 4"]'::jsonb, 0, 'Correct option: A. 9, 4 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-64', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  64, '64', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'There are 6 equally spaced points A, B, C, D, E and F marked on a circle with radius R. How many convex heptagons of distinctly different areas can be drawn using these points as vertices?',
  '["7!*6","7𝐶5","7!","Same area"]'::jsonb, 3, 'Correct option: D. Same area is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-65', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  65, '65', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', '17 students are present in a class. In how many ways, can they be made to stand in 2 circles of 8 and 9 students?',
  '["17C9 x 9! X 8!","17C9 x 8! X 7!","8! X 7!","17C8 x 8! X 9!"]'::jsonb, 1, 'Correct option: B. 17C9 x 8! X 7! is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-66', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  66, '66', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Amir is a window cleaner. He uses the following formula to calculate the amount to charge his customers: Charge = Rs 20+4n, where n is the number of windows a house has. If a house has 7 windows, how much would Amir charge?',
  '["48","28","68","20"]'::jsonb, 0, 'Correct option: A. 48 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-67', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  67, '67', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'The inverse of the function f(x)=2x-3 is',
  '["(x+3)/2","(x-3)/2","(x+2)/3","(x-2)/ 3"]'::jsonb, 0, 'Correct option: A. (x+3)/2 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-68', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  68, '68', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Which of these lines is parallel to the line 2y = x+7',
  '["𝑦 = 2𝑥 − 9","𝑦 = 2𝑥 + 3","𝑦 = 0","𝑦 = 𝑥/ 2 − 9"]'::jsonb, 3, 'Correct option: D. 𝑦 = 𝑥/ 2 − 9 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-69', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  69, '69', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Find x if 𝐿𝑜𝑔𝑥(9/25) = 2',
  '["5/3","5/6","3/5","6/ 5"]'::jsonb, 2, 'Correct option: C. 3/5 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-ii-70', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  70, '70', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'The period of 𝑦 = 2𝑆𝑖𝑛(𝑥 − 𝜋/3) 𝑖𝑠',
  '["2𝜋","𝜋/3","𝜋","−𝜋"]'::jsonb, 0, 'Correct option: A. 2𝜋 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-iii-1', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  1, 'Descriptive 1', 'Mathematics',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Question No 1: Let 𝑎, 𝑏 and 𝑐 be distinct nonzero real numbers such that 1 1 1a b cb c a+ = + = + Prove that |𝑎𝑏𝑐| = 1.',
  '[]'::jsonb, null, 'Let the common value be k. Subtracting the equal expressions gives factors of the form (a-b)(abc+1), (b-c)(abc+1), and (c-a)(abc+1). Since a, b, and c are distinct, at least one difference is nonzero, so abc=-1 and therefore |abc|=1.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2023-final-maths-2023-4566955-part-iii-2', 'published', 'mathematics-2023-final-maths-2023-4566955', 'Mathematics',
  2, 'Descriptive 2', 'Mathematics',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2023, 'NSTC 2023 Mathematics Paper', 'Question No 2: In , and , ,ABC AB AC D E FDelta= are on ,,AB BC CA , such that .DE EF FD== Prove that )1 2 ( .DEB ADF CFEangle = angle + angle -',
  '[]'::jsonb, null, 'Since DE=EF=FD, triangle DEF is equilateral. Rotate the configuration by 60 degrees around the equilateral triangle and use corresponding angles on sides AB, BC, and CA. The exterior angle at E is then the half-sum of the two companion angles at D and F, giving the required angle relation.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-1', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  1, '1', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'During cellular respiration breakdown of glucose occurs in',
  '["Vacuole","Golgi complex","Cytoplasm","Mitochondria"]'::jsonb, 3, 'Most aerobic breakdown of glucose occurs in mitochondria.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-2', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  2, '2', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The following rays can cause cancer',
  '["X-rays","Gamma rays","Alpha and beta particles","All of these"]'::jsonb, 3, 'X-rays, gamma rays, alpha particles, and beta particles can all be ionizing cancer risks.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-3', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  3, '3', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The hypothesis that stands the test of time are called',
  '["Law","Null Hypothesis","Principle","Theories"]'::jsonb, 3, 'Hypotheses that remain supported by repeated testing are called theories.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-4', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  4, '4', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Electric intensity is a',
  '["vector","scalar","basic","none of these"]'::jsonb, 0, 'Electric field intensity has both magnitude and direction, so it is a vector.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-5', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  5, '5', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'One coulomb is equal to the charge of------------------------electrons.',
  '["6.25 x 10^19","6.24 x 10^18","6.24 x 10^17","6.25 x 10^18"]'::jsonb, 3, 'One coulomb is approximately the charge magnitude of 6.25 x 10^18 electrons.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-6', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  6, '6', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The phenomenon of emission of light in a chemical reaction is known as',
  '["Chemiluminescence","Photosensitization","Luminescence","None of these"]'::jsonb, 0, 'Light emission during a chemical reaction is chemiluminescence.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-7', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  7, '7', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Name the device used to measure the number of nuclear disintegration per minute',
  '["Cyclotron","Geiger counter","Cloud chamber","Mass spectrograph"]'::jsonb, 1, 'A Geiger counter measures counts from nuclear disintegrations.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-8', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  8, '8', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Which of the following bonds must be present in alkynes?',
  '["Single bond","Double bond","triple bond","Hydrogen bond"]'::jsonb, 2, 'Alkynes contain at least one carbon-carbon triple bond.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-9', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  9, '9', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'When a solution contains equal concentration of hydroxyl and hydrogen ions its pH will be around',
  '["0","14","7","10"]'::jsonb, 2, 'Equal hydrogen and hydroxide ion concentrations make the solution neutral, around pH 7.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-10', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  10, '10', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Which is the most reactive element in the given list?',
  '["Fluorine","Oxygen","Nitrogen","Iodine"]'::jsonb, 0, 'Fluorine is the most reactive element among the listed choices.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-11', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  11, '11', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'A quadrilateral with vertices at ( ) ( ) ( ) ( )0, –1 , 3,1 , 3, 1 , 0,1- is a __________.',
  '["kite","square","parallelogram","rectangle"]'::jsonb, 3, 'The listed vertices form a rectangle rather than a square or kite.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-12', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  12, '12', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The center of the circle, __________.',
  '["is a point on the circle","lies outside of the circle","lies inside of the circle","none of these"]'::jsonb, 2, 'The center of a circle lies inside the circle, not on the circumference.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-13', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  13, '13', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'What is the sum of all the divisors of 600?',
  '["2060","1860","2160","1890"]'::jsonb, 1, '600=2^3*3*5^2, so the divisor sum is (1+2+4+8)(1+3)(1+5+25)=1860.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-14', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  14, '14', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'What is the sum of the first nine prime numbers?',
  '["100","98","80","77"]'::jsonb, 0, 'The first nine primes sum to 2+3+5+7+11+13+17+19+23=100.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-15', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  15, '15', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The equations 2x+7=3 and bx - 10 = -2 have the same solution. What is the value of b?',
  '["-4","6","2","3/ 2"]'::jsonb, 0, '2x+7=3 gives x=-2; substituting in bx-10=-2 gives b=-4.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-16', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  16, '16', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'A ball of mass m falls from rest onto a floor, from a height h. It makes elastic collisions with the floor repeatedly. The force exerted by it on the floor, averaged over a long time, is',
  '["mg","2 mg","3 mg","proportional to m and h"]'::jsonb, 0, 'Over a long time the average upward impulse from the floor balances the ball''s weight, so the average force is mg.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-17', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  17, '17', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'While passing over an obstacle a light ray slightly bends round the corner. The phenomenon is known as__',
  '["Scattering","Polarisation","Diffraction","Refraction"]'::jsonb, 2, 'Bending of light around an obstacle is diffraction.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-18', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  18, '18', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'What is the orbital velocity of geo stationary satellite?',
  '["4.15 km/s","2.78 km/s","3.08 km/s","6. 66 km/s"]'::jsonb, 2, 'A geostationary satellite moves at about 3.08 km/s in orbit.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-19', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  19, '19', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'What is the direction of electric and magnetic fields in an electromagnetic wave?',
  '["parallel to each other","at 90° to each other","at 45° to each other","at 120° to each other"]'::jsonb, 1, 'Electric and magnetic fields in an electromagnetic wave are perpendicular to each other.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-i-20', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  20, '20', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'What is the time period of a seconds pendulum?',
  '["0.5 second","1.0 seconds","1.5 seconds","2.0 seconds"]'::jsonb, 3, 'A seconds pendulum has a time period of 2.0 seconds.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-21', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  21, '21', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The points ( ) ( ) ( )1, 1 , 4, 2 , 10,8- in the plane are',
  '["Concyclic","Collinear","Concurrent","None of these"]'::jsonb, 1, 'Correct option: B. Collinear is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-22', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  22, '22', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Let the central angle subtended by two points on a circle is 120° . Then the inscribed angle subtended by those points is ________.',
  '["240°","90°","60°","180°"]'::jsonb, 2, 'Correct option: C. 60° is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-23', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  23, '23', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'How many different tangents can be drawn on a circle?',
  '["1","2","4","Infinite"]'::jsonb, 3, 'Correct option: D. Infinite is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-24', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  24, '24', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The angle between the tangents at the ends of two perpendicular radii is _________.',
  '["0°","45°","90°","180°"]'::jsonb, 2, 'Correct option: C. 90° is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-25', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  25, '25', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The tangents on the end points of a diameter of a circle are always',
  '["Collinear","Concurrent","Parallel","None of these"]'::jsonb, 2, 'Correct option: C. Parallel is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-26', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  26, '26', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Consider a triangle 𝐴𝐵𝐶 with ∠𝐴 = 45° and ∠𝐵 = 5°. What is the type of ∆𝐴𝐵𝐶?',
  '["Right Angle","Isosceles","Acute","Obtuse"]'::jsonb, 3, 'Correct option: D. Obtuse is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-27', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  27, '27', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'All the ________ in a plane are similar',
  '["Triangles","Parallelograms","Circles","None of these"]'::jsonb, 2, 'Correct option: C. Circles is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-28', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  28, '28', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'If a line intersects two concentric circles with centre O at A, B, C and D, then',
  '["AB = CD","AB > CD","AB < CD","None of these"]'::jsonb, 0, 'Correct option: A. AB = CD is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-29', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  29, '29', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'If 𝑎 and 𝑏 are coprime integers, which of the following must also be coprime?',
  '["𝑎2 and 𝑏2","𝑎 + 1 and 𝑏 + 1","2𝑎 and 2𝑏","𝑎 + 𝑏 and 𝑎𝑏"]'::jsonb, 0, 'Correct option: A. 𝑎2 and 𝑏2 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-30', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  30, '30', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Sum of two different prime numbers is a',
  '["Prime number","Composite number","Either Prime or composite","None of these"]'::jsonb, 2, 'Correct option: C. Either Prime or composite is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-31', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  31, '31', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'How many distinct prime factors does 216 × 34 × 52 have?',
  '["3","6","9","12"]'::jsonb, 0, 'Correct option: A. 3 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-32', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  32, '32', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'What is the remainder when 72024 is divided by 13?',
  '["3","7","12","1"]'::jsonb, 0, 'Correct option: A. 3 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-33', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  33, '33', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'What is the least number that is exactly divisible by all the numbers from 1 to 10?',
  '["5040","2520","1024","2048"]'::jsonb, 1, 'Correct option: B. 2520 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-34', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  34, '34', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'What is the units digit of 22047 × 311?',
  '["1","7","6","9"]'::jsonb, 2, 'Correct option: C. 6 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-35', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  35, '35', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'What is the value of 4234 mod 11',
  '["8","7","1","3"]'::jsonb, 3, 'Correct option: D. 3 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-36', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  36, '36', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'If 𝑝 is a prime number greater than 3, what is the remainder when 𝑝2 is divided by 12?',
  '["1","5","7","9"]'::jsonb, 0, 'Correct option: A. 1 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-37', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  37, '37', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'If 𝑛 is a positive integer such that 𝑛2 is divisible by 72, then the smallest 𝑛 is',
  '["6","9","12","24"]'::jsonb, 2, 'Correct option: C. 12 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-38', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  38, '38', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'From a group 7 men and 6 women, five persons are to be selected to form a committee so that at least 3 men are there in the committee. In how many ways can it be done?',
  '["756","564","735","None of the above"]'::jsonb, 0, 'Correct option: A. 756 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-39', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  39, '39', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The 6th and 17th terms of an A.P. are 19 and 41 respectively. Find the 40th term',
  '["87","78","88","None of the above"]'::jsonb, 0, 'Correct option: A. 87 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-40', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  40, '40', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'There are 10 true-false questions in an examination. These questions can be answered in',
  '["20 ways","100 ways","512 ways","1024 ways"]'::jsonb, 3, 'Correct option: D. 1024 ways is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-41', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  41, '41', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Mayur travels from Mumbai to Jammu in 7 different ways. But he is allowed to return to Mumbai by any way except the one he used earlier. In how many ways can he complete his journey?',
  '["49","42","48","6"]'::jsonb, 1, 'Correct option: B. 42 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-42', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  42, '42', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'What is the Cartesian product of set A and set B, if the set A = {1, 2} and set B = {a, b}?',
  '["{ (1, a), (1","(2, a), (b, b) } (b) { (1, 1), (2, 2), (a, a), (b, b) }","{ (1, a), (2, a), (1, b), (2, b) }","{ (1, 1), (a, a), (2, a), (1, b) }"]'::jsonb, 2, 'Correct option: C. { (1, a), (2, a), (1, b), (2, b) } is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-43', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  43, '43', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Let the players who play cricket be 12, the ones who play football 10, those who play only cricket are 6, then the number of players who play only football are ___________, assuming there is a total of 16 players.',
  '["16","8","4","10"]'::jsonb, 2, 'Correct option: C. 4 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-44', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  44, '44', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'How many terms are in the expansion of (2𝑥 − 1 𝑦) 10 ?',
  '["9","10","11","12"]'::jsonb, 2, 'Correct option: C. 11 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-45', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  45, '45', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The value of (50 4 ) + ∑ (56 − 𝑟 3 )6 𝑟=1 is',
  '["(55 4 )","(55 3 )","(56 3 )","( 56 4 )"]'::jsonb, 3, 'Correct option: D. ( 56 4 ) is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-46', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  46, '46', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'There are 27 points in a plane. 5, 10 and 15 points are collinear on distinct lines. By joining these points, how many distinct lines can be formed?',
  '["194","170","435","None of these"]'::jsonb, 0, 'Correct option: A. 194 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-47', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  47, '47', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', '10 boys and 10 girls sit alternately in a row and then alternately along a circle. The ratio of number of ways of sitting in a row to the number of ways of sitting along a circle is',
  '["5","10","15","20"]'::jsonb, 3, 'Correct option: D. 20 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-48', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  48, '48', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'If 𝑛(𝐴) = 20 and 𝑛(𝐵) = 30 and 𝑛(𝐴 ∪ 𝐵) = 40 then 𝑛(𝐴 ∩ 𝐵) is?',
  '["20","30","40","10"]'::jsonb, 3, 'Correct option: D. 10 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-49', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  49, '49', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Which of the following function is not a mathematics function?',
  '["many-to-one","one-to-many","one-to-one","all of the mentioned above"]'::jsonb, 1, 'Correct option: B. one-to-many is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-50', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  50, '50', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'A ball is dropped from a height of 49 m. The quadratic equation 𝑑(𝑡) =– 𝑡2 + 49 provides information about the height of the ball d, after t seconds. In how many seconds, does the ball hit the ground?',
  '["3","5","7","9"]'::jsonb, 2, 'Correct option: C. 7 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-51', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  51, '51', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Cities A and B are 45 miles apart. Alicia lives in A and Beth lives in B. Alicia bikes towards B at 18 miles per hour. Leaving at the same time, Beth bikes toward A at 12 miles per hour. How many miles from City A will they be when they meet?',
  '["20","24","25","27"]'::jsonb, 3, 'Correct option: D. 27 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-52', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  52, '52', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The sum of two numbers is S. Suppose 3 is added to each number and then each of the resulting numbers is doubled. What is the sum of the final two numbers?',
  '["2S+3","2S+12","2S+6","2S+2"]'::jsonb, 1, 'Correct option: B. 2S+12 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-53', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  53, '53', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Given that a, b, and c are non-zero real numbers, define (a,b,c)= a/b + b/c + c/a. Find (2,12,9)',
  '["4","5","6","7"]'::jsonb, 2, 'Correct option: C. 6 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-54', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  54, '54', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'For how many positive integers m does there exist at least one positive integer n such that 𝑚𝑛 < 𝑚 + 𝑛?',
  '["Infinitely many","1","2","4"]'::jsonb, 0, 'Correct option: A. Infinitely many is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-55', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  55, '55', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Cindy was asked by her teacher to subtract 3 from a certain number and then divide the result by 9. Instead, she subtracted 9 and then divided the result by 3, giving an answer of 43. What would her answer have been had she worked the problem correctly?',
  '["15","34","43","51"]'::jsonb, 0, 'Correct option: A. 15 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-56', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  56, '56', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Compute the sum of all the roots of (2x+3)(x-4)+(2x+3)(x-6)=0',
  '["4","7/2","0","6"]'::jsonb, 1, 'Correct option: B. 7/2 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-57', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  57, '57', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'You and five friends need to raise 1500 dollars in donations for a charity, dividing the fundraising equally. How many dollars will each of you need to raise?',
  '["300","1500","9000","250"]'::jsonb, 3, 'Correct option: D. 250 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-58', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  58, '58', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'A company sells peanut butter in cylindrical jars. Marketing research suggests that using wider jars will increase sales. If the diameter of the jars is increased by 25% without altering the volume, by what percent must the height be decreased?',
  '["26","16","36","46"]'::jsonb, 2, 'Correct option: C. 36 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-59', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  59, '59', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'If A and B are matrices of order three then Det(AB) equals',
  '["Det(A)+Det(","Det(A)Det(B)","0","None of these"]'::jsonb, 1, 'Correct option: B. Det(A)Det(B) is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-60', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  60, '60', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The LCM of two numbers is 7200, and their HCF is 180. If one number is 360, then the second number is',
  '["480","360","720","1440"]'::jsonb, null, 'The printed data are inconsistent. If lcm(a,b)=7200, gcd(a,b)=180, and a=360, then a valid integer pair cannot satisfy all three conditions; the product formula would require b=3600, which is not listed.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-61', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  61, '61', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'In a group of 8 people, how many ways can you choose a committee of 3 people if two specific individuals refuse to work together?',
  '["6","84","12","24"]'::jsonb, null, 'The correct count is C(8,3)-6=50 because six committees contain both conflicting people, but 50 is not among the printed options.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-62', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  62, '62', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Determine the sum of the geometric series: 4 + 2 + 1 + 1 2⁄ + ….',
  '["7","9","8","10"]'::jsonb, 2, 'Correct option: C. 8 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-63', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  63, '63', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'A recipe calls for a ratio of 2 cups of flour to 1 cup of sugar. If you want to use 4 cups of sugar, how much flour should you use?',
  '["8 cups","6 cups","4 cups","2 cups"]'::jsonb, 0, 'Correct option: A. 8 cups is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '/api/storage/paper-assets/mathematics-2024-final-maths-2024-640e2ac/figures/q63-p6-1.webp', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-64', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  64, '64', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'If p is inversely proportional to q, and p=8 when q=6, what is the value of q when p=12?',
  '["6","5","2","4"]'::jsonb, 3, 'Correct option: D. 4 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-65', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  65, '65', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'If the sides of two similar triangles are in the ratio 2:3, what is the ratio of their areas?',
  '["1:1","1:2","2:3","4: 9"]'::jsonb, 3, 'Correct option: D. 4: 9 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-66', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  66, '66', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'Simplify log3(27) − log3(9).',
  '["1","2","3","4"]'::jsonb, 0, 'Correct option: A. 1 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'mathematics-2024-final-maths-2024-640e2ac-part-ii-67', 'published', 'mathematics-2024-final-maths-2024-640e2ac', 'Mathematics',
  67, '67', 'Mathematics',
  'Mathematics MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Mathematics MCQs', 'NSTC',
  2024, 'NSTC 2024 Mathematics Paper', 'The linear combination of gcd(252, 198) = 18 is?',
  '["252 ∗ 4 – 198 ∗ 5","252 ∗ 5 – 198 ∗ 4","252 ∗ 5 – 198 ∗ 2","252 ∗ 4 – 198 ∗ 4"]'::jsonb, 0, 'Correct option: A. 252 ∗ 4 – 198 ∗ 5 is the verified choice from the source paper; it follows from the standard mathematics result needed by the prompt.',
  6, '', '{}'::jsonb
)
on conflict (id) do update set
  status = excluded.status,
  paper_id = excluded.paper_id,
  paper_subject = excluded.paper_subject,
  number = excluded.number,
  display_number = excluded.display_number,
  subject = excluded.subject,
  topic = excluded.topic,
  difficulty = excluded.difficulty,
  type = excluded.type,
  section = excluded.section,
  section_title = excluded.section_title,
  exam = excluded.exam,
  year = excluded.year,
  source = excluded.source,
  prompt = excluded.prompt,
  options = excluded.options,
  answer = excluded.answer,
  solution = excluded.solution,
  page = excluded.page,
  figure = excluded.figure,
  metadata = excluded.metadata;

commit;
