-- Question seed chunk 1
-- Generated by scripts/generate_supabase_seed_sql.ts.
-- Run the schema migration first, then run these seed files in filename order.

begin;

insert into public.questions (
  id, status, paper_id, paper_subject, number, display_number, subject, topic,
  difficulty, type, section, section_title, exam, year, source, prompt,
  options, answer, solution, page, figure, metadata
) values
(
  'biology-2022-final-biology-2022-068e355-part-i-1', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  1, '1', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'In multicellular organisms, similar cells are organized into groups, called',
  '["Organ","Organ system","Tissues","Individual"]'::jsonb, 2, 'Similar cells that perform a common function form tissues.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-2', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  2, '2', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The process by which one diploid cell divides to generate four haploid daughter cells is called',
  '["Mitosis","Prophase","Meiosis","Anaphase"]'::jsonb, 2, 'Meiosis starts from one diploid cell and produces four haploid daughter cells.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-3', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  3, '3', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Red blood cells are also called erythrocytes and transport',
  '["nerve impulse","Oxygen","water","food"]'::jsonb, 1, 'Erythrocytes are red blood cells, and their main transport role is oxygen carriage.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-4', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  4, '4', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'A series of hypothesis supported by the results of many tests is called',
  '["Scientific law","Theory","Data","Deduction"]'::jsonb, 1, 'A hypothesis repeatedly supported by tests becomes a scientific theory.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-5', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  5, '5', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Artificial cleaning of blood is known as',
  '["Dialysis","Diabetes","Lithotripsy","Both a & b"]'::jsonb, 0, 'Dialysis is the artificial removal of wastes from blood.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-6', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  6, '6', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which acid is present in vinegar?',
  '["Acetic Acid","Formic Acid","Oxalic Acid","Hydro Chloric Acid"]'::jsonb, 0, 'Vinegar is an aqueous solution whose characteristic acid is acetic acid.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-7', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  7, '7', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which metal exist in fluid form at standard temperature and pressure conditions?',
  '["Mercury","Bromine","Sodium","Calcium"]'::jsonb, 0, 'Mercury is the metal that is liquid at standard temperature and pressure.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-8', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  8, '8', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which one is not the contribution of Dalton in Chemistry?',
  '["Atomic theory","Dalton Law","Law of multiple proportion","Law of conservation of mass"]'::jsonb, 3, 'The law of conservation of mass is associated with Lavoisier, not Dalton.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-9', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  9, '9', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'What is the empirical formula of Urea?',
  '["CH4ON2","C3H4NO3","CH3NO2","C6H5NO2"]'::jsonb, 0, 'Urea has molecular formula CH4N2O, so the empirical formula is the same.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-10', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  10, '10', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which vitamin is known as ascorbic acid?',
  '["Vitamin A","Vitamin B","Vitamin C","Vitamin D"]'::jsonb, 2, 'Ascorbic acid is the chemical name of vitamin C.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-11', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  11, '11', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'If ð‘Ž âˆ— b = a-b+ab, then 2 âˆ— 5 + 5 âˆ— 2 is',
  '["14","16","20","none of these"]'::jsonb, 2, 'Using a*b=a-b+ab gives 2*5=7 and 5*2=13, so the sum is 20.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-12', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  12, '12', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which of the fractions below is closest to 1?',
  '["8/7","9/10","10/11","11/10"]'::jsonb, 2, '10/11 is about 0.909, closer to 1 than the other listed fractions.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-13', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  13, '13', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', '62 + |6| + |âˆ’6| âˆ’ 62 is equal to',
  '["-6","0","6","12"]'::jsonb, 3, 'The squared terms cancel, leaving |6|+|-6|=12.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-14', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  14, '14', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', '5^5 / 5^4 is equal to',
  '["1","5","25","125"]'::jsonb, 1, 'Dividing powers with the same base subtracts exponents: 5^5/5^4=5.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-15', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  15, '15', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', '(ð‘Žð‘š)ð‘› =',
  '["ð‘Žð‘šð‘›","ð‘Žð‘š+ð‘›","ð‘Žð‘šð‘›","None of these"]'::jsonb, 0, 'A power raised to a power multiplies exponents: (a^m)^n=a^(mn).',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-16', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  16, '16', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which is a derived unit?',
  '["meter","second","kilogram","newton"]'::jsonb, 3, 'The newton is derived from base SI units as kg m s^-2.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-17', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  17, '17', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'A boy weighing 500 newtons takes 50. seconds to climb a flight of stairs 18 meters high. His power output vertically is',
  '["9,000 W","4,000 W","1,400 W","180 W"]'::jsonb, 3, 'Power equals work/time=(500 N)(18 m)/50 s=180 W.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-18', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  18, '18', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which net charge could be found on an object?',
  '["+3.2Ã— 10â€“18 C","-1.8Ã— 10â€“18 C","+2.4Ã— 10â€“19 C","-0.80Ã— 10â€“19 C"]'::jsonb, 0, 'Net charge must be an integer multiple of the elementary charge 1.6 x 10^-19 C.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-19', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  19, '19', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Compared to insulators, metals are better conductors of electricity because metals contain more free',
  '["protons","electrons","positive ions","negative ions"]'::jsonb, 1, 'Metals conduct well because they contain many mobile electrons.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-i-20', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  20, '20', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which two quantities are measured in the same units',
  '["momentum and work","energy and power","mechanical energy and heat","work and power"]'::jsonb, 2, 'Mechanical energy and heat are both measured in joules.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-21', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  21, '21', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'In which phase of Meiosis the homologous chromosomes separated from each other',
  '["prophase 1","telophase 1","anaphase 1","Metaphase 1"]'::jsonb, 2, 'Correct option: C. anaphase 1 is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-22', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  22, '22', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'An unbroken series of species arranged in ancestors to descendent sequence with each later species having evolved from one that immediately preceded it is called',
  '["Biome","Phyletic lineage","Community","Population"]'::jsonb, 1, 'Correct option: B. Phyletic lineage is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-23', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  23, '23', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Lipids are synthesized in',
  '["Rough endoplasmic reticulum","Chloroplast","Ribosomes","Smooth endoplasmic reticulum"]'::jsonb, 3, 'Correct option: D. Smooth endoplasmic reticulum is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-24', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  24, '24', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which of the following is an example of carnivorous plant',
  '["Sundew","Sunflower","Sphagnum","None of the above"]'::jsonb, 0, 'Correct option: A. Sundew is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-25', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  25, '25', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which of the macronutrient is involved in closing and opening of stomata',
  '["potassium","sulpher","phosphorus","calcium"]'::jsonb, 0, 'Correct option: A. potassium is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-26', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  26, '26', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'It is possible to date the rocks by comparing the amount of specific radioactive isotopes they contain. Which of the statement is correct in this respect?',
  '["Older sediment layers have an equal amount of these radioactive isotopes as that of the young ones","Older sediment layers have less amount of these radioactive isotopes as that of the young ones","Older sediment layers have a greater amount of these radioactive isotopes as that of the young ones","Older sediment layers did not have these radioactive isotopes"]'::jsonb, 1, 'Correct option: B. Older sediment layers have less amount of these radioactive isotopes as that of the young ones is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-27', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  27, '27', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The part of earth inhabited by organisms communities is known as',
  '["Atmosphere","Ecosystem","Biosphere","Environment"]'::jsonb, 2, 'Correct option: C. Biosphere is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-28', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  28, '28', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The scientific name of onion is',
  '["Asterias rubens","Brassica","Allium cepa","Allium sativum"]'::jsonb, 2, 'Correct option: C. Allium cepa is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-29', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  29, '29', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The tissues covers the outside of body and lines organs and cavities are called',
  '["Connective tissue","Epithelial tissue","Muscle tissue","Simple tissue"]'::jsonb, 1, 'Correct option: B. Epithelial tissue is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-30', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  30, '30', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Movement of molecules from an area of higher concentration to the area of lower concentration along the concentration gradient is called',
  '["Facilitated diffusion","Osmosis","Diffusion","Active transport"]'::jsonb, 2, 'Correct option: C. Diffusion is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-31', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  31, '31', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The meristem located on the tips roots and shoots is called',
  '["Apical meristem","Intercalary meristem","Lateral meristem","Cork cambium"]'::jsonb, 0, 'Correct option: A. Apical meristem is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-32', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  32, '32', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Maximum number of species of living things on earth are',
  '["Algae","Fungi","Insects","Protozoa"]'::jsonb, 2, 'Correct option: C. Insects is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-33', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  33, '33', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The major component of fungi cell wall is',
  '["Cellulose","Peptidoglycan","Cholesterol","Chitin"]'::jsonb, 3, 'Correct option: D. Chitin is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-34', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  34, '34', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The Ozone layer is contained within the',
  '["troposphere","mesosphere","thermosphere","stratosphere"]'::jsonb, 3, 'Correct option: D. stratosphere is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-35', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  35, '35', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Astronauts may use which technique to grow fruits and vegetables',
  '["Tissue culture techniques","Cloning","Pasteurization","Hydroponic culture technique"]'::jsonb, 3, 'Correct option: D. Hydroponic culture technique is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-36', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  36, '36', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The process in which cell takes solid materials are called',
  '["Endocytosis","Exocytosis","Phagocytosis","Pinocytosis"]'::jsonb, 2, 'Correct option: C. Phagocytosis is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-37', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  37, '37', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which blood vessel contain valves',
  '["Arteries","Veins","Capillaries","Arterioles"]'::jsonb, 1, 'Correct option: B. Veins is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-38', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  38, '38', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Pyruvic acid is converted to Acetyl CoA before entering in',
  '["Calvin cycle","ETC","glycolysis","Krebs Cycle"]'::jsonb, 3, 'Correct option: D. Krebs Cycle is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-39', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  39, '39', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Scurvy result from the lack of vitamin',
  '["Vitamin A","Vitamin B","Vitamin C","Vitamin D"]'::jsonb, 2, 'Correct option: C. Vitamin C is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-40', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  40, '40', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Biological sciences have a set methodology and it is based on',
  '["Experimental inquiry","Esthetic preference","Philosophical ideas","Imaginations"]'::jsonb, 0, 'Correct option: A. Experimental inquiry is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-41', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  41, '41', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which of the following is not an example of continuous evolution?',
  '["Skin color","Body weight","Rose flower color","None of the these"]'::jsonb, 2, 'Correct option: C. Rose flower color is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-42', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  42, '42', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The process of loss of water from plant surface through evaporation is called',
  '["Transpiration","Transportation","Respiration","Transfusion"]'::jsonb, 0, 'Correct option: A. Transpiration is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-43', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  43, '43', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'A molecule of DNA contains all of the following EXCEPT',
  '["Deoxyribose sugars","Polypeptide bonds","Phosphodiester bonds","Nitrogenous bases"]'::jsonb, 1, 'Correct option: B. Polypeptide bonds is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-44', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  44, '44', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which of the following is universal donor blood group',
  '["A","B","AB","O"]'::jsonb, 3, 'Correct option: D. O is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-45', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  45, '45', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Contraction of atria pushes the blood toward ventricles, this is called',
  '["atria systole","ventricles diastole","atrial diastole","ventricular systole"]'::jsonb, 0, 'Correct option: A. atria systole is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-46', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  46, '46', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'According to Mendelâ€™s law of independent assortment what will be the typical ratio of F2 in a dihybrid cross',
  '["3:1","5:1","1:2:1","9:3:3:1"]'::jsonb, 3, 'Correct option: D. 9:3:3:1 is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-47', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  47, '47', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Principle of 3R means',
  '["Reduce, Renew, Recycle","Reduce, Reuse, Recycle","Reduce, Re-establish, Renew","Reduce, Reforest, Recycle"]'::jsonb, 1, 'Correct option: B. Reduce, Reuse, Recycle is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-48', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  48, '48', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Spectrococcus carries out a process called',
  '["Alchohol fermentation","Oxalate synthesis","Malate synthesis","Lactic acid fermentation"]'::jsonb, 3, 'Correct option: D. Lactic acid fermentation is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-49', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  49, '49', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which of the following enzymes dissolve blood clots',
  '["Interferons","Haemophillia","Urokinase","All of these"]'::jsonb, 2, 'Correct option: C. Urokinase is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-50', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  50, '50', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The primary structure of protein refers to the',
  '["Sequence of sugar molecules in the protein","Sequence of the DNA in the genome","Sequence of peptide bonds in the protein molecule","Sequence of amino acids in the polypeptide chain"]'::jsonb, 3, 'Correct option: D. Sequence of amino acids in the polypeptide chain is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-51', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  51, '51', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Sleep movements are a type of',
  '["Turgor movements","Growth movements","Tactic movements","Paratonic movements"]'::jsonb, 0, 'Correct option: A. Turgor movements is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-52', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  52, '52', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The extreme change in pH results in',
  '["Change in ionization of amino acids at the active site of the enzyme","Change in the ionization of the substrate","Denaturation of the enzyme","Increase in the reaction rate"]'::jsonb, 2, 'Correct option: C. Denaturation of the enzyme is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-53', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  53, '53', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Pathogen contains special proteins known as',
  '["Antigen","Antibody","Functional protein","Resistant protein"]'::jsonb, 0, 'Correct option: A. Antigen is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-54', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  54, '54', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Stomata present in leaves involves in the process of',
  '["Respiration","Gaseous exchange","Photosynthesis","Both a & b"]'::jsonb, 3, 'Correct option: D. Both a & b is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-55', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  55, '55', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'In the human body, 99% of total mass is formed of',
  '["16 bioelements","12 bioelements","10 bioelements","6 bioelements"]'::jsonb, 3, 'Correct option: D. 6 bioelements is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-56', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  56, '56', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Thick muscular structure present below the lungs',
  '["Ribs","Intercoastal muscles","Diaphragm","None of these"]'::jsonb, 2, 'Correct option: C. Diaphragm is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-57', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  57, '57', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The one which is a weed killer',
  '["IAA","NAA","2 4-D","GA"]'::jsonb, 2, 'Correct option: C. 2 4-D is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-58', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  58, '58', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Amount of Carbon dioxide in inspired air',
  '["20%","0.56%","4%","0.04%"]'::jsonb, 3, 'Correct option: D. 0.04% is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-59', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  59, '59', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Primary chemical stimulus for breathing is the concentration of',
  '["Carbon dioxide in blood","Carbon dioxide in muscles","Oxygen in blood","Oxygen in muscles"]'::jsonb, 0, 'Correct option: A. Carbon dioxide in blood is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-60', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  60, '60', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Maintenance of internal body conditions at equilibrium, despite changes in the external environment',
  '["Homeostasis","Osmoregulation","Excretion","None of these"]'::jsonb, 0, 'Correct option: A. Homeostasis is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-61', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  61, '61', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'U-shape structure present in Nephron known as',
  '["Renal tubule","Loop of Henle","Collecting duct","Medulla"]'::jsonb, 1, 'Correct option: B. Loop of Henle is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-62', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  62, '62', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Glomerulus is',
  '["Cup shape structure","Functional unit of kidney","Network of capillaries","None of these"]'::jsonb, 2, 'Correct option: C. Network of capillaries is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-63', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  63, '63', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Which of the following occurs in anaerobic respiration but not in aerobic respiration?',
  '["Release of CO2","Reduction of NAD","Formation of ATP","Production of ethanol from acetaldehyde"]'::jsonb, 3, 'Correct option: D. Production of ethanol from acetaldehyde is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-64', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  64, '64', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Chemical coordination is brought about by',
  '["Nervous system","Endocrine system","Both a & b","None of these"]'::jsonb, 1, 'Correct option: B. Endocrine system is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-65', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  65, '65', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Fusion of the bones at joint may occur and joints may become totally immoveable in',
  '["Gout","Arthritis","Osteoporosis","Osteocytes"]'::jsonb, 1, 'Correct option: B. Arthritis is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-66', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  66, '66', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Calyx is a collection of',
  '["Petals only","Sepals and petals","Corolla","Sepals only"]'::jsonb, 3, 'Correct option: D. Sepals only is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-67', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  67, '67', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Hydra and corals also reproduce by means of',
  '["Sexual reproduction","Budding","Asexual reproduction","Both a & b"]'::jsonb, 1, 'Correct option: B. Budding is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-68', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  68, '68', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Scar present on a seed coat known as',
  '["Radicle","Plumule","Hilum","Epicotyl"]'::jsonb, 2, 'Correct option: C. Hilum is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-69', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  69, '69', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The one which is not a globular protein',
  '["Anti Rh-antibody","Enzyme","Myosin","Hemoglobin"]'::jsonb, 2, 'Correct option: C. Myosin is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-ii-70', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  70, '70', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'The basic structural unit of a chromosome is',
  '["The centromere","Nucleosome","Telomere","Histone"]'::jsonb, 1, 'Correct option: B. Nucleosome is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-iii-1', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  1, 'Descriptive 1', 'Biology',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Question 1: In the context of genetics, what is the reason of normal (healthy) and diseased siblings in same family if the parents are normal?',
  '[]'::jsonb, null, 'Normal parents can have diseased children when both parents are heterozygous carriers of a recessive disease allele. The parents show the dominant healthy phenotype, but each child has a 25% chance of inheriting both recessive alleles and being affected.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-iii-2', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  2, 'Descriptive 2', 'Biology',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Question 2: Why is shivering likely during the onset of a fever?',
  '[]'::jsonb, null, 'At the onset of fever, pyrogens raise the hypothalamic temperature set point. The body is then colder than the new set point, so involuntary muscle contractions (shivering) generate heat until body temperature rises.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-iii-3', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  3, 'Descriptive 3', 'Biology',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Question 3: What advantages did plants gain from the evolution of secondary growth?',
  '[]'::jsonb, null, 'Secondary growth gives plants thicker vascular tissue and wood. This increases mechanical support, allows greater height, improves water and food transport, adds protective bark, and supports long-lived perennial growth.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-iii-4', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  4, 'Descriptive 4', 'Biology',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Question 4: Why doesnâ€™t gastric juice destroy the stomach cells that make it?',
  '[]'::jsonb, null, 'The stomach is protected by a mucus-bicarbonate barrier, tight epithelial junctions, rapid cell replacement, and secretion of pepsin as inactive pepsinogen. These protections keep acid and enzymes from digesting the stomach wall.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-iii-5', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  5, 'Descriptive 5', 'Biology',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Question 5: A zoo animal eating ample food shows signs of malnutrition, how will you (as a researcher) determine which nutrient is lacking in its diet?',
  '[]'::jsonb, null, 'Compare the animal''s diet with its requirements, record symptoms, and run blood or tissue tests for likely deficiencies. Then give controlled supplements one at a time and monitor weight, behavior, coat, blood markers, and recovery to identify the missing nutrient.',
  null, '', '{}'::jsonb
),
(
  'biology-2022-final-biology-2022-068e355-part-iii-6', 'published', 'biology-2022-final-biology-2022-068e355', 'Biology',
  6, 'Descriptive 6', 'Biology',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2022, 'NSTC 2022 Biology Paper', 'Question 6: A person traveling from Pakistan to America suffers from sleep disorder. What is the reason? ----',
  '[]'::jsonb, null, 'The sleep disorder is jet lag. Rapid travel across time zones disrupts the circadian rhythm because light cues, melatonin secretion, sleep timing, and local clock time no longer match.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-1', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  1, '1', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'During cellular respiration breakdown of glucose occurs in',
  '["Vacuole","Golgi complex","Mitochondria","Cytoplasm"]'::jsonb, 2, 'Most aerobic breakdown of glucose occurs in mitochondria.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-2', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  2, '2', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The hypothesis that stands the test of time are called',
  '["Law","Null hypothesis","Principle","Theories"]'::jsonb, 3, 'Hypotheses that remain supported by repeated testing are called theories.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-3', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  3, '3', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Cancer is disease of',
  '["Simple cell division","Uncontrolled cell division","Controlled cell division","Accelerated cell division"]'::jsonb, 1, 'Cancer is characterized by uncontrolled cell division.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-4', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  4, '4', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'A conjugate acid is a specie formed by accepting a',
  '["Electron pair","Neutron","Proton","Electron"]'::jsonb, 2, 'A conjugate acid forms when a base accepts a proton.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-5', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  5, '5', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'In which phase of Meiosis the homologous chromosomes separated from each other',
  '["prophase 1","telophase 1","anaphase 1","metaphase 1"]'::jsonb, 2, 'Homologous chromosomes separate during anaphase I of meiosis.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-6', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  6, '6', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'All of the following substance are crystalline except',
  '["Ice","Diamond","Sucrose","Plastic"]'::jsonb, 3, 'Plastic is generally amorphous rather than crystalline.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-7', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  7, '7', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Diameter of an atom in the order of',
  '["0.2Î¼m","0.2mm","0.2nm","0.2pm"]'::jsonb, 2, 'Atomic diameters are on the order of 10^-10 m, or about 0.2 nm.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-8', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  8, '8', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Which of the following is not a macromolecule',
  '["Sand","Hemoglobin","Diamond","Maltose"]'::jsonb, 3, 'Maltose is a small disaccharide, not a macromolecule.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-9', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  9, '9', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'About how many elements in the Periodic Table are Metals',
  '["60%","65%","70%","75%"]'::jsonb, 3, 'Most periodic-table elements are metals; 75 percent is the closest listed value.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-10', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  10, '10', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Plasma is used in',
  '["Florescent bulb","Neon signs","Laser","All of these"]'::jsonb, 3, 'Plasmas are used in fluorescent lamps, neon signs, and some laser systems.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-11', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  11, '11', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The distance between the points (-2, 2) and (1, 6) is',
  '["25 units","5 units","7 units","none of these"]'::jsonb, 1, 'The distance is sqrt((1+2)^2+(6-2)^2)=sqrt(25)=5.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-12', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  12, '12', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Angles that sum up to 90 Â° are known as',
  '["complementary angles","vertical angles","reflective angles","supplementary angles"]'::jsonb, 0, 'Angles whose measures add to 90 degrees are complementary.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-13', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  13, '13', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Total number of lines passing through the point (0,0) are',
  '["0","1","2","infinity"]'::jsonb, 3, 'Infinitely many lines can pass through a single point in a plane.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-14', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  14, '14', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The coordinates of the midpoint of points in plane with coordinates (âˆ’2,8) and (8, âˆ’2) is',
  '["(0,0)","(3,3)","(2,2)","(8,8)"]'::jsonb, 1, 'The midpoint is ((-2+8)/2,(8-2)/2)=(3,3).',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-15', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  15, '15', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'If ð‘¥ + 1 ð‘¥ = 2, then the value of ð‘¥2 + 1 ð‘¥2 is',
  '["1/4","1","3","2"]'::jsonb, 3, 'If x+1/x=2, then x^2+1/x^2=(x+1/x)^2-2=2.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-16', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  16, '16', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'A net force of 10. Newtons accelerates an object at 5.0 m/s 2. What net force would be required to accelerate the same object at 1.0 m/s2?',
  '["1.0 N","2.0 N","5 N","10 N"]'::jsonb, 1, 'The mass is F/a=10/5=2 kg, so a 1.0 m/s^2 acceleration needs 2.0 N.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-17', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  17, '17', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'A 1,200-kilogram car traveling at 10. m/s hits a tree and is brought to rest in 0.10 second. What is the magnitude of the average force acting on the car to bring it to rest?',
  '["1.2 x 10^2 N","1.2 x 10^3 N","1.2 x 10^4 N","1.2 x 10^5 N"]'::jsonb, 3, 'Average force is change in momentum over time: (1200 kg)(10 m/s)/0.10 s=1.2 x 10^5 N.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-18', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  18, '18', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'When a neutral metal sphere is charged by contact with a positively charged glass rod, the sphere',
  '["loses electrons","loses protons","gains electrons","gains protons"]'::jsonb, 0, 'A positively charged rod removes electrons from the neutral metal during contact.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-19', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  19, '19', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'An electric iron operating at 120 volts draws 10. Amperes of current. How much heat energy is delivered by the iron in 30 Seconds?',
  '["3.0 x 10^2 J","3.6 x 10^3 J","1.2 x 10^3 J","3.6 x 10^4 J"]'::jsonb, 3, 'Heat delivered is VIt=(120 V)(10 A)(30 s)=3.6 x 10^4 J.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-i-20', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  20, '20', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'A radar gun can determine the speed of a moving automobile by measuring the difference infrequency between emitted and reflected radar waves. This process illustrates',
  '["resonance","diffraction","the Doppler effect","refraction"]'::jsonb, 2, 'Speed measurement from a frequency shift of reflected waves uses the Doppler effect.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-21', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  21, '21', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The process in which the homologous chromosomes line up with each other and form a pair is called',
  '["Synapsis","Bivalent","Chiasmata","Crossing over"]'::jsonb, 0, 'Correct option: A. Synapsis is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-22', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  22, '22', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The major component of fungi cell wall is',
  '["Peptidoglycan","Cellulose","Chitin","Lipid"]'::jsonb, 2, 'Correct option: C. Chitin is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-23', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  23, '23', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The shrinking of cytoplasm is called',
  '["Plasmolysis","Cytolysis","Cytocompression","Cytodialation"]'::jsonb, 0, 'Correct option: A. Plasmolysis is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-24', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  24, '24', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'What is the shape of the rings present in trachea?',
  '["C-shaped cartilaginous","U-shaped fibrous","B-shaped cartilaginous","D-shaped fibrous"]'::jsonb, 0, 'Correct option: A. C-shaped cartilaginous is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-25', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  25, '25', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The main cause of lung cancer include',
  '["Water contamination","Bacterial infection","Un-sterilized syringe","Carcinogens"]'::jsonb, 3, 'Correct option: D. Carcinogens is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-26', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  26, '26', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The tissues which attach muscles to bones are called?',
  '["tendons","ligaments","Cartilage","Connective"]'::jsonb, 0, 'Correct option: A. tendons is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-27', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  27, '27', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Cartilage and bones are--------------- tissues.',
  '["Ground","Supporting","Connective","Socket"]'::jsonb, 1, 'Correct option: B. Supporting is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-28', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  28, '28', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Cellular respiration is--------------------------reaction',
  '["Physical","Oxidation- reduction","Reduction","Oxidation"]'::jsonb, 1, 'Correct option: B. Oxidation- reduction is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-29', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  29, '29', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'T and B cells are',
  '["RBC","Natural killer cells","Lymphocytes","Macrophyes"]'::jsonb, 2, 'Correct option: C. Lymphocytes is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-30', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  30, '30', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Gaseous exchange in leaf occurs through',
  '["Lenticles","Stomata","Epidermis","Cuticle"]'::jsonb, 1, 'Correct option: B. Stomata is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-31', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  31, '31', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The nasal cavity opens into the',
  '["Oral cavity","Larynx","Nasopharynx","Lungs"]'::jsonb, 2, 'Correct option: C. Nasopharynx is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-32', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  32, '32', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The tissues cover the outside of body and lines organs and cavities are called',
  '["Connective tissue","Epithelial tissue","Muscle tissue","Epidermis"]'::jsonb, 1, 'Correct option: B. Epithelial tissue is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-33', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  33, '33', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', '-------------------are the most abundant species on planet Earth.',
  '["Human","Protoza","Insects","Bacteria"]'::jsonb, 2, 'Correct option: C. Insects is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-34', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  34, '34', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Erythrocytes transport----------------------?',
  '["Nerve impulse","Food","Water","Oxygen"]'::jsonb, 3, 'Correct option: D. Oxygen is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-35', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  35, '35', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Which blood vessel contain valves?',
  '["arteries","veins","capillaries","arterioles"]'::jsonb, 1, 'Correct option: B. veins is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-36', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  36, '36', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Glucagon is produced by',
  '["Thyroid glands","Sweat glands","Gastric glands","Pancreas"]'::jsonb, 3, 'Correct option: D. Pancreas is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-37', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  37, '37', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Plants store large amount of water in their cells for',
  '["turgidity","dormancy","flaccidity","pollination"]'::jsonb, 0, 'Correct option: A. turgidity is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-38', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  38, '38', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Despite eating a carb-rich meal, the blood glucose level remains at',
  '["1 g/L","2 g/L","10 g/L","20 g/L"]'::jsonb, 0, 'Correct option: A. 1 g/L is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-39', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  39, '39', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The trees which shed leaves annually remove',
  '["Nutrients","Oil and bark","Harmless metabolites","Excretory products"]'::jsonb, 3, 'Correct option: D. Excretory products is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-40', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  40, '40', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Cells involved in photosynthesis and respiration during day are',
  '["Epidermal cells","Pericycle cells","Mesophyll cells","Cortical cells"]'::jsonb, 2, 'Correct option: C. Mesophyll cells is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-41', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  41, '41', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Some gaseous exchange in young stem and leaves occur through',
  '["Mid-rib","Petiole","Cuticle","Thalamus"]'::jsonb, 2, 'Correct option: C. Cuticle is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-42', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  42, '42', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', '---------------------is the functional unit of environment.',
  '["Genus","Ecosystem","Community","Biome"]'::jsonb, 1, 'Correct option: B. Ecosystem is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-43', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  43, '43', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The alternate form of a gene is called',
  '["Allele","Sister chromosome","Replicate","Genovar"]'::jsonb, 0, 'Correct option: A. Allele is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-44', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  44, '44', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Expired drugs can cause damage to',
  '["Brain","Kidney","Heart","Stomach"]'::jsonb, 1, 'Correct option: B. Kidney is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-45', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  45, '45', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Spinal cord is the continuation of',
  '["medulla oblangata","cerebellum","hypothlamus","temporal lob"]'::jsonb, 0, 'Correct option: A. medulla oblangata is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-46', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  46, '46', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The study of external structural characterization is called',
  '["Cytology","Anatomy","Histology","Morphology"]'::jsonb, 3, 'Correct option: D. Morphology is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-47', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  47, '47', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Peritoneum contains',
  '["Somatic and visceral afferent nerves","Celiac, superior and inferior mesenteric vessels","Stomach, liver, pancrease","All of these"]'::jsonb, 3, 'Correct option: D. All of these is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-48', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  48, '48', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The study of internal structural characterization is called',
  '["Cytology","Anatomy","Histology","Morphology"]'::jsonb, 1, 'Correct option: B. Anatomy is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-49', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  49, '49', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The drugs used to reduce pain are known as',
  '["Analgesics","Antiseptic","Antibiotic","Sedative"]'::jsonb, 0, 'Correct option: A. Analgesics is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-50', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  50, '50', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The most rapidly dwindling resource in the world is ______',
  '["Air","Water","Forests","Sunlight"]'::jsonb, 2, 'Correct option: C. Forests is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-51', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  51, '51', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'When the platelets count is too high, it can cause',
  '["blood cancer","blood clots, arterio-sclerosis","bleeding, trauma, heart attack","high cholesterol, heart attack"]'::jsonb, 1, 'Correct option: B. blood clots, arterio-sclerosis is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-52', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  52, '52', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Which of the following is NOT an example of continuous evolution?',
  '["Antibiotic resistance","Body weight","Skin color","Insect wings"]'::jsonb, 0, 'Correct option: A. Antibiotic resistance is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-53', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  53, '53', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Which of following WBC is involved in preventing blood clotting',
  '["neutrophils","eosinophils","monocytes","basophils"]'::jsonb, 3, 'Correct option: D. basophils is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-54', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  54, '54', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'During day, O2 is produced in the mesophyll cells as a',
  '["By product","Waste","Toxic product","End product"]'::jsonb, 0, 'Correct option: A. By product is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-55', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  55, '55', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Carbon containing fossils fuels are?',
  '["minerals and carbonate","peat, coal, petroleum","biodiesel","diamond"]'::jsonb, 1, 'Correct option: B. peat, coal, petroleum is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-56', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  56, '56', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Seedless fruit plants are propagated by',
  '["grafting","cloning","cutting","binary fission"]'::jsonb, 2, 'Correct option: C. cutting is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-57', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  57, '57', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Diagphragm is a',
  '["Thick bony structure present above the lungs","Thick covering around the lungs","A thin bony structure present above the lungs","A thick muscular structure present below the lungs"]'::jsonb, 3, 'Correct option: D. A thick muscular structure present below the lungs is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-58', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  58, '58', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The cancer with highest death rate in the world is------------------',
  '["Lung cancer","Blood cancer","Skin cancer","Stomach cancer"]'::jsonb, 0, 'Correct option: A. Lung cancer is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-59', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  59, '59', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Elastic cartilage is found in',
  '["trachea","Pinna, epiglottis","spine","Hip joint"]'::jsonb, 1, 'Correct option: B. Pinna, epiglottis is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-60', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  60, '60', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Which of these is an antiviral protein?',
  '["Urokinase","Thymosin","Interferon","Cecropin"]'::jsonb, 2, 'Correct option: C. Interferon is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-61', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  61, '61', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The sensory layer of eye is',
  '["Retina","Iris","Cornea","Sclera"]'::jsonb, 0, 'Correct option: A. Retina is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-62', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  62, '62', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Night blindness can be avoided by taking----',
  '["Lodosporin","Vitamin A","Vitamin B","Vitamin K"]'::jsonb, 1, 'Correct option: B. Vitamin A is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-63', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  63, '63', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Nonsene codons?',
  '["UAA, UAU, UUA","UGA, UAG, UAA","UGG, UGA, UAU","UGG,UAA,UAG"]'::jsonb, 1, 'Correct option: B. UGA, UAG, UAA is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  5, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-64', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  64, '64', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The lens found in human eye is',
  '["Concave","biconvex","Progressive","Trifocal lens"]'::jsonb, 1, 'Correct option: B. biconvex is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-65', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  65, '65', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'A vector is selected for the transfer of the isolated gene of interest to the',
  '["Host cell","DNA","Donor organism","None of these"]'::jsonb, 0, 'Correct option: A. Host cell is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-66', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  66, '66', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The observable set of characteristics of an organism',
  '["Genotype","DNA","Phenotype","Genes"]'::jsonb, 2, 'Correct option: C. Phenotype is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-67', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  67, '67', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Pathogens contain proteins called',
  '["lipoproteins","histones","antibodies","antigens"]'::jsonb, 3, 'Correct option: D. antigens is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-68', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  68, '68', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Nitrogen fixation is conversion of nitrogen into',
  '["Nitric oxide","Nitric acid","Nitrate and ammonia","Nitrous oxides"]'::jsonb, 2, 'Correct option: C. Nitrate and ammonia is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-69', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  69, '69', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Drugs used to relieve persistent or severe pain in chronic diseases e.g., cancer?',
  '["Disprin","Narcotics","Sedatives","Panadol"]'::jsonb, 1, 'Correct option: B. Narcotics is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-ii-70', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  70, '70', 'Biology',
  'Biology MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Biology MCQs', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'The vector DNA and the inserted gene of interest are collectively called as',
  '["Transformed DNA","Transcript DNA","Recombinant DNA","Mutated DNA"]'::jsonb, 2, 'Correct option: C. Recombinant DNA is the verified choice from the source paper; it follows from the standard biology result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-iii-1', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  1, 'Descriptive 1', 'Biology',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Question 1: In the context of genetics, what is the reason of normal (healthy) and diseased siblings in same family if the parents are normal?',
  '[]'::jsonb, null, 'Normal parents can have diseased children if both are carriers for a recessive allele. Each parent can pass the recessive allele without being diseased, and a child receiving both recessive copies will show the disorder.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-iii-2', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  2, 'Descriptive 2', 'Biology',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Question 2: Why is shivering likely during the onset of a fever?',
  '[]'::jsonb, null, 'During fever onset the hypothalamic set point rises. The body responds as if it is too cold, so skeletal muscles shiver to produce heat and raise body temperature.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-iii-3', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  3, 'Descriptive 3', 'Biology',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Question 3: A drug for Leukemia is not broken down in the stomach and is well absorbed by the intestine. The traces/molecules of the drug found in the patientâ€™s blood do not match to the form that was swallowed by the patient. What is the possible explanation for this?',
  '[]'::jsonb, null, 'The swallowed drug was likely metabolized after absorption, especially by intestinal or liver enzymes during first-pass metabolism. The blood therefore contains metabolite forms rather than the exact molecule originally swallowed.',
  null, '', '{}'::jsonb
),
(
  'biology-2023-final-biology-2023-a4481c6-part-iii-4', 'published', 'biology-2023-final-biology-2023-a4481c6', 'Biology',
  4, 'Descriptive 4', 'Biology',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2023, 'NSTC 2023 Biology Paper', 'Question 4: The cell goes through a cycle that consists of four stages: G1, S, G2, and M. After DNA is duplicated in eukaryotes, it must be bound to histones. This required the synthesis of hundreds of millions of new protein molecules. When in the cell cycle stage (G1, S, G2, or M) histones are produced?',
  '[]'::jsonb, null, 'Histones are produced mainly during S phase, when DNA is being replicated. Newly made DNA must be packaged immediately into nucleosomes, so histone synthesis is coordinated with DNA synthesis.',
  null, '', '{}'::jsonb
)
on conflict (id) do update set
  status = excluded.status,
  paper_id = excluded.paper_id,
  paper_subject = excluded.paper_subject,
  number = excluded.number,
  display_number = excluded.display_number,
  subject = excluded.subject,
  topic = excluded.topic,
  difficulty = excluded.difficulty,
  type = excluded.type,
  section = excluded.section,
  section_title = excluded.section_title,
  exam = excluded.exam,
  year = excluded.year,
  source = excluded.source,
  prompt = excluded.prompt,
  options = excluded.options,
  answer = excluded.answer,
  solution = excluded.solution,
  page = excluded.page,
  figure = excluded.figure,
  metadata = excluded.metadata;

commit;
