-- Question seed chunk 3
-- Generated by scripts/generate_supabase_seed_sql.ts.
-- Run the schema migration first, then run these seed files in filename order.

begin;

insert into public.questions (
  id, status, paper_id, paper_subject, number, display_number, subject, topic,
  difficulty, type, section, section_title, exam, year, source, prompt,
  options, answer, solution, page, figure, metadata
) values
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-22', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  22, '22', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which acid is found in bee string?',
  '["Formic Acid","Citric Acid","Oxalic Acid","Tartaric Acid"]'::jsonb, 0, 'Correct option: A. Formic Acid is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-23', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  23, '23', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which process is used to produce baking soda?',
  '["Soda Process","Chlor-Alkali process","Solvary Process","None of these"]'::jsonb, 2, 'Correct option: C. Solvary Process is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-24', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  24, '24', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'A balances chemical equation always obeys.',
  '["Law of conservation of energy","Law of thermal equilibrium","Law of conservation of mass","All these laws"]'::jsonb, 2, 'Correct option: C. Law of conservation of mass is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-25', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  25, '25', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which isotope is used in nuclear reactor to generate electricity?',
  '["C-60","U-235","Na-24","C-13"]'::jsonb, 1, 'Correct option: B. U-235 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-26', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  26, '26', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'The percentage of Nitrogen in urea is',
  '["86","66","46","26"]'::jsonb, 2, 'Correct option: C. 46 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-27', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  27, '27', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'How much volume of oxygen at STP in liter is required to completely burn 8g of methane gas?',
  '["44.8","22.4","11.2","5.6"]'::jsonb, 1, 'Correct option: B. 22.4 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-28', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  28, '28', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which element has the same oxidation state in all of its compounds?',
  '["Hydrogen","Carbon","Oxygen","Fluorine"]'::jsonb, 3, 'Correct option: D. Fluorine is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-29', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  29, '29', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'The elements of group 16 are also known as',
  '["Halogens","Chalcogens","Noble gas","ericogens"]'::jsonb, 1, 'Correct option: B. Chalcogens is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-30', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  30, '30', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'The oxidation reaction is',
  '["Loss of electron","Removal of the hydrogen atom","Addition of an oxygen atom","All of the above"]'::jsonb, 3, 'Correct option: D. All of the above is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-31', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  31, '31', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'What is the color of the flame test for sodium?',
  '["Green","Yellow","Red","Violet"]'::jsonb, 1, 'Correct option: B. Yellow is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-32', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  32, '32', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Acetic acid was added into a solid â€œSâ€ kept in test tube. A colorless and odorless gas â€œGâ€ was evolved which turn lime water milky. It was concluded that',
  '["Solid â€œSâ€ is sodium acetate and the gas â€œGâ€ is CO2","Solid â€œSâ€ is sodium bicarbonate and the gas â€œGâ€ is SO2","Solid â€œSâ€ is sodium hydroxide and the gas â€œGâ€ is CO2","Solid â€œSâ€ is sodium bicarbonate and the gas â€œGâ€ is CO2"]'::jsonb, 3, 'Correct option: D. Solid â€œSâ€ is sodium bicarbonate and the gas â€œGâ€ is CO2 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-33', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  33, '33', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'The numbers of single and double bonds present in benzene are',
  '["9 and 6","9 and 3","3 and 3","3 and 9"]'::jsonb, 1, 'Correct option: B. 9 and 3 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-34', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  34, '34', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which of the following is not endothermic process?',
  '["Evaporation of water","Sublimation of iodine","Dilution of an acid","Melting of ice"]'::jsonb, 2, 'Correct option: C. Dilution of an acid is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-35', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  35, '35', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which gas is used to fill the plastic bags containing potato chips?',
  '["Hydrogen","Nitrogen","Oxygen","Chlorine"]'::jsonb, 1, 'Correct option: B. Nitrogen is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-36', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  36, '36', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which allotropic form of carbon is a good conductor of heat and electricity?',
  '["Graphite","Diamond","Charcoal","None of these"]'::jsonb, 0, 'Correct option: A. Graphite is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-37', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  37, '37', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which formula represents bleaching powder?',
  '["CaO","CaCl2","Ca(OCl)2","Ca(OH)2"]'::jsonb, 2, 'Correct option: C. Ca(OCl)2 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-38', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  38, '38', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Fatty acid become rancid due to the process of',
  '["Reduction","Oxidation","Corrosion","Decomposition"]'::jsonb, 1, 'Correct option: B. Oxidation is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-39', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  39, '39', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'The oxides of metalloids are ___________ in nature.',
  '["Basic","Acidic","Neutral","Amphoteric"]'::jsonb, 3, 'Correct option: D. Amphoteric is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-40', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  40, '40', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which of the following is not a standard condition?',
  '["298K","100 kPa","100 atm","1 mol dmâ€“3 solutions"]'::jsonb, 2, 'Correct option: C. 100 atm is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-41', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  41, '41', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Elements with more than 57 electrons require',
  '["f-orbital","d-orbital","p-orbital","s- orbital"]'::jsonb, 0, 'Correct option: A. f-orbital is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-42', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  42, '42', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'The decrease in the force of attraction is due to the increase in the',
  '["distance only","shielding effect only","number of electrons","distance and shielding effect"]'::jsonb, 3, 'Correct option: D. distance and shielding effect is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-43', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  43, '43', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'The chemical reaction between carbonyl compounds and DNPH is an example of',
  '["Condensation reaction","Substitution reaction","Addition reaction","CO2 (d) Elimination reaction"]'::jsonb, 0, 'Correct option: A. Condensation reaction is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-44', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  44, '44', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'In electrolysis of aqueous Copper(II) Sulfate (CuSO4) with Carbon (C) electrode,',
  '["oxygen gas is given off at anode","Sulfur dioxide is given off at anode","oxygen gas is given off at cathode","Sulfur dioxide is given off at cathode"]'::jsonb, 0, 'Correct option: A. oxygen gas is given off at anode is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-45', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  45, '45', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'The correct order of increasing nucleophilicity is',
  '["Clâ€“ < Brâ€“ < Iâ€“","Brâ€“ < Clâ€“ < Iâ€“","Iâ€“ < Brâ€“ < Clâ€“","Iâ€“ < Clâ€“ < Brâ€“"]'::jsonb, 0, 'Correct option: A. Clâ€“ < Brâ€“ < Iâ€“ is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-46', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  46, '46', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'The incorrect statement about mineral acid is',
  '["They have simpler molecular structure","They are more corrosive","They are commonly found in nature","They are man made"]'::jsonb, 2, 'Correct option: C. They are commonly found in nature is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-47', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  47, '47', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which among the following reagent can be used to distinguish between CH2BrCH=CH2 from CH3CH=CHBr?',
  '["Br2/CCl4","cold KMnO4","AgNO3/C2H5OH","Ag(NH3)2OH"]'::jsonb, 2, 'Correct option: C. AgNO3/C2H5OH is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-48', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  48, '48', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Depletion of the ozone layer is caused due to',
  '["Ferrocene","Fullerenes","Freons","Grephene"]'::jsonb, 2, 'Correct option: C. Freons is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-49', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  49, '49', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Find the volume of O2 required to burn 1 L of propane completely, measured at 0 â„ƒ temperature and 1 atm pressure',
  '["10 L","7 L","6 L","5 L (a) distance only (b) shielding effect only (c) number of electrons (d) distance and shielding effect"]'::jsonb, 3, 'Correct option: D. 5 L (a) distance only (b) shielding effect only (c) number of electrons (d) distance and shielding effect is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-50', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  50, '50', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Why do we boil the extract with conc. HNO3 in Lassaigneâ€™s test for halogens?',
  '["to increase the concentration of NO3â€“ ions","to increase the solubility product of AgCl","it increases the precipitation of AgCl","for the decomposition of Na2S and NaCN formed"]'::jsonb, 3, 'Correct option: D. for the decomposition of Na2S and NaCN formed is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-51', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  51, '51', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'The solution which is used to detect the presence of aldehyde or ketone is',
  '["2,4-dinitrophenylhydrazine","benzene solution","Tollen''s reagent","none of above"]'::jsonb, 0, 'Correct option: A. 2,4-dinitrophenylhydrazine is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-52', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  52, '52', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which of the following is the major organic product obtained from the following reaction? H O Ag2O NH4OH, H2O ethanol',
  '["Structure A","Structure B","Structure C","Structure D"]'::jsonb, 2, 'Correct option: C. Structure C is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '/paper-assets/chemistry-2022-final-chemistry-2022-b9f5031/figures/q52-p7-manual.webp', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-53', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  53, '53', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'When dichromate (VI) ion becomes reduced to chromium (III) ion, a change of color occurs from',
  '["purple to pink","purple to colorless","orange to purple","orange to green"]'::jsonb, 3, 'Correct option: D. orange to green is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-54', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  54, '54', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'A container has an equal mass of H2, O2 and CH4 at 27â„ƒ, the ratio of their volume is',
  '["16:8:1","8:1:2","16:1:2","8:16:1"]'::jsonb, 2, 'Correct option: C. 16:1:2 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-55', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  55, '55', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'What is the molecular weight of Potash alum?',
  '["458 g/mol","216 g/mol","474 g/mol","356 g/mol"]'::jsonb, 2, 'Correct option: C. 474 g/mol is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-56', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  56, '56', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'When a small number of acids or bases are added to zwitterion ion, it resists a change in: 1',
  '["temperature","volatility","polarity","pH"]'::jsonb, 3, 'Correct option: D. pH is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-57', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  57, '57', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'A mixture of low boiling hydrocarbons is called',
  '["coal","petroleum","natural gas","Liquid Petroleum Gas (LPG)"]'::jsonb, 3, 'Correct option: D. Liquid Petroleum Gas (LPG) is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-58', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  58, '58', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which of the following is widely used in the oxy-acetylene welding and cutting metals?',
  '["ethylene","acetylene","phenol","methanol"]'::jsonb, 1, 'Correct option: B. acetylene is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-59', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  59, '59', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'If graphite (C) is used as an electrode in the presence of concentrated Hydrochloric Acid (HCl), at the anode',
  '["chlorine gas is produced","oxygen gas is produced","hydrogen gas is produced","hydrogen chloride is produced"]'::jsonb, 0, 'Correct option: A. chlorine gas is produced is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-60', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  60, '60', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Process in which coal is heated in the absence of air at high temperature and converted into coal gas, coal tar, and coke is called',
  '["Destructive distillation","Distillation","Burning of coal","Burning of oxygen"]'::jsonb, 0, 'Correct option: A. Destructive distillation is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-61', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  61, '61', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'To conduct electricity, the ionic metals shall be',
  '["Dissolved in water","Finely grinded","In molten form","On ionic lattice"]'::jsonb, 2, 'Correct option: C. In molten form is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-62', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  62, '62', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'What is true about impurities?',
  '["They lower the boiling point","They lower the freezing point","The lower the melting point","They raise the melting point"]'::jsonb, 2, 'Correct option: C. The lower the melting point is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-63', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  63, '63', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'If the nucleon (mass) and proton (atomic) number is 40 and 20 respectively, the element is?',
  '["Chlorine","Phosphorous","Potassium","Calcium"]'::jsonb, 3, 'Correct option: D. Calcium is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-64', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  64, '64', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'All of these radicals have a valency of 2, except',
  '["SO4","CO3","NH4","MgCO3"]'::jsonb, 2, 'Correct option: C. NH4 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-65', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  65, '65', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Valency of plumbum can be',
  '["2 or 4","4 or 6","3 or 5","2 or 3"]'::jsonb, 0, 'Correct option: A. 2 or 4 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-66', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  66, '66', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Give that a certain organic compounds absorbs light in the visible region, it CANNOT be true that it',
  '["is aromatic","is an alkane","is colored","contains a nitro group"]'::jsonb, 1, 'Correct option: B. is an alkane is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-67', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  67, '67', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Rank the following forces from weakest to strongest between two elementary particles: gravitational / covalent / London dispersion / nuclear',
  '["nuclear < London < covalent < gravitational","nuclear < covalent < London < gravitational","nuclear < gravitational < covalent < London","gravitational < London < covalent < nuclear"]'::jsonb, 3, 'Correct option: D. gravitational < London < covalent < nuclear is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-68', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  68, '68', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', '0.36 moles of each aluminium and oxygen react with each other to produce aluminium oxide. The amount of product formed is',
  '["0.18 mole","0.27 mole","0.24 mole","0.09 mole"]'::jsonb, 0, 'Correct option: A. 0.18 mole is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-69', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  69, '69', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Which substance has the highest percentage by mass of Nitrogen?',
  '["NH4NO3 Mr=80","(NH4)2SO4 Mr =132","CO(NH2)2 Mr=60","(NH4)3PO4 Mr=149"]'::jsonb, 2, 'Correct option: C. CO(NH2)2 Mr=60 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-ii-70', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  70, '70', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Suppose the entropy of a system increases with increase in some parameter X. What will be the effect on entropy at equilibrium state of the system, when the parameter will be decreased?',
  '["the entropy decrease","the entropy increase","the entropy remains constant","Condition is wrong, entropy does not change with any parameter"]'::jsonb, 0, 'Correct option: A. the entropy decrease is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2022-final-chemistry-2022-b9f5031-part-iii-1', 'published', 'chemistry-2022-final-chemistry-2022-b9f5031', 'Chemistry',
  71, 'Descriptive 1', 'Chemistry',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2022, 'NSTC 2022 Chemistry Paper', 'Chemistry-Descriptive Questions [Max points 30: All questions carry equal points] Question 1. What are the two tests to distinguish between glucose and fructose? Question 2. How does the half-life period depend on the initial concentration in the case of reactions of the first and nth order? Question 3. What does acetic acid and sodium acetate form? Question 4. Why Carboxylic is acidic? -',
  '[]'::jsonb, null, 'Glucose and fructose can be distinguished by Seliwanoff''s test: fructose, a ketose, gives a rapid cherry-red color, while glucose reacts slowly. Bromine water also oxidizes glucose readily to gluconic acid, whereas fructose is not oxidized under the same mild conditions. For kinetics, a first-order half-life is independent of initial concentration, while for an nth-order reaction (n>1), t1/2 is proportional to 1/a^(n-1). Acetic acid plus sodium acetate forms an acidic buffer. Carboxylic acids are acidic because the carboxylate ion formed after H+ loss is resonance-stabilized and further stabilized by the electron-withdrawing carbonyl group.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-1', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  1, '1', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'During cellular respiration breakdown of glucose occurs in',
  '["Vacuole","Golgi complex","Mitochondria","Cytoplasm"]'::jsonb, 2, 'Most aerobic breakdown of glucose occurs in mitochondria.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-2', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  2, '2', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'The hypothesis that stands the test of time are called',
  '["Law","Null hypothesis","Principle","Theories"]'::jsonb, 3, 'Hypotheses that remain supported by repeated testing are called theories.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-3', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  3, '3', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Cancer is disease of',
  '["Simple cell division","Uncontrolled cell division","Controlled cell division","Accelerated cell division"]'::jsonb, 1, 'Cancer is characterized by uncontrolled cell division.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-4', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  4, '4', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'A conjugate acid is a specie formed by accepting a',
  '["Electron pair","Neutron","Proton","Electron"]'::jsonb, 2, 'A conjugate acid forms when a base accepts a proton.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-5', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  5, '5', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'In which phase of Meiosis the homologous chromosomes separated from each other',
  '["prophase 1","telophase 1","anaphase 1","metaphase 1"]'::jsonb, 2, 'Homologous chromosomes separate during anaphase I of meiosis.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-6', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  6, '6', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'All of the following substance are crystalline except',
  '["Ice","Diamond","Sucrose","Plastic"]'::jsonb, 3, 'Plastic is generally amorphous rather than crystalline.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-7', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  7, '7', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Diameter of an atom in the order of',
  '["0.2 Î¼m","0.2 mm","0.2 nm","0.2 pm"]'::jsonb, 2, 'Atomic diameters are on the order of 10^-10 m, or about 0.2 nm.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-8', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  8, '8', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which of the following is not a macromolecule',
  '["Sand","Hemoglobin","Diamond","Maltose"]'::jsonb, 3, 'Maltose is a small disaccharide, not a macromolecule.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-9', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  9, '9', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'About how many elements in the Periodic Table are Metals',
  '["60%","65%","70%","75%"]'::jsonb, 3, 'Most periodic-table elements are metals; 75 percent is the closest listed value.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-10', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  10, '10', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Plasma is used in',
  '["Florescent bulb","Neon signs","Laser","All of these"]'::jsonb, 3, 'Plasmas are used in fluorescent lamps, neon signs, and some laser systems.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-11', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  11, '11', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'The distance between the points (-2, 2) and (1, 6) is',
  '["25 units","5 units","7 units","none of these"]'::jsonb, 1, 'The distance is sqrt((1+2)^2+(6-2)^2)=sqrt(25)=5.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-12', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  12, '12', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Angles that sum up to 90 Â° are known as',
  '["complementary angles","vertical angles","reflective angles","supplementary angles"]'::jsonb, 0, 'Angles whose measures add to 90 degrees are complementary.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-13', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  13, '13', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Total number of lines passing through the point (0,0) are',
  '["0","1","2","infinity"]'::jsonb, 3, 'Infinitely many lines can pass through a single point in a plane.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-14', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  14, '14', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'The coordinates of the midpoint of points in plane with coordinates (âˆ’2,8) and (8, âˆ’2) is',
  '["(0,0)","(3,3)","(2,2)","(8,8)"]'::jsonb, 1, 'The midpoint is ((-2+8)/2,(8-2)/2)=(3,3).',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-15', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  15, '15', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'If ð‘¥ + 1 ð‘¥ = 2, then the value of ð‘¥2 + 1 ð‘¥2 is',
  '["1/4","1","3","2"]'::jsonb, 3, 'If x+1/x=2, then x^2+1/x^2=(x+1/x)^2-2=2.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-16', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  16, '16', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'A net force of 10. Newtons accelerates an object at 5.0 m/s 2. What net force would be required to accelerate the same object at 1.0 m/s2?',
  '["1.0 N","2.0 N","5 N","10 N"]'::jsonb, 1, 'The mass is F/a=10/5=2 kg, so a 1.0 m/s^2 acceleration needs 2.0 N.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-17', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  17, '17', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'A 1,200-kilogram car traveling at 10. m/s hits a tree and is brought to rest in 0.10 second. What is the magnitude of the average force acting on the car to bring it to rest?',
  '["1.2 x 10^2 N","1.2 x 10^3 N","1.2 x 10^4 N","1.2 x 10^5 N"]'::jsonb, 3, 'Average force is change in momentum over time: (1200 kg)(10 m/s)/0.10 s=1.2 x 10^5 N.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-18', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  18, '18', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'When a neutral metal sphere is charged by contact with a positively charged glass rod, the sphere',
  '["loses electrons","loses protons","gains electrons","gains protons"]'::jsonb, 0, 'A positively charged rod removes electrons from the neutral metal during contact.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-19', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  19, '19', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'An electric iron operating at 120 volts draws 10. Amperes of current. How much heat energy is delivered by the iron in 30 Seconds?',
  '["3.0 x 10^2 J","3.6 x 10^3 J","1.2 x 10^3 J","3.6 x 10^4 J"]'::jsonb, 3, 'Heat delivered is VIt=(120 V)(10 A)(30 s)=3.6 x 10^4 J.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-i-20', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  20, '20', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'A radar gun can determine the speed of a moving automobile by measuring the difference infrequency between emitted and reflected radar waves. This process illustrates',
  '["resonance","diffraction","the Doppler effect","refraction"]'::jsonb, 2, 'Speed measurement from a frequency shift of reflected waves uses the Doppler effect.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-21', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  21, '21', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which of the following isnâ€™t a state function',
  '["Internal energy","Enthalpy","Gibbs free energy","Heat"]'::jsonb, 3, 'Correct option: D. Heat is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-22', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  22, '22', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'The velocity of the photon',
  '["Is independent of its wavelength","Equal to the square of amplitude","Depends upon its frequency","Depends upon source"]'::jsonb, 0, 'Correct option: A. Is independent of its wavelength is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-23', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  23, '23', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Hydrogen effuses four times more rapidly than volume of an unknown gas molar mass of unknown gas should be',
  '["16 gmol-1","32 gmol-1","48 gmol-1","64 gmol-1"]'::jsonb, 1, 'Correct option: B. 32 gmol-1 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-24', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  24, '24', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which one of the following is a buffer solution',
  '["Solution of CuSO4","Blood","Glue","Brine"]'::jsonb, 1, 'Correct option: B. Blood is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-25', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  25, '25', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which substance can be used for disinfecting water',
  '["KMnO4","Alums","Ozone","All"]'::jsonb, 3, 'Correct option: D. All is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-26', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  26, '26', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'How many chiral compounds are possible on monochlorination of 2â€“methyl butane',
  '["2","4","6","8"]'::jsonb, 1, 'Correct option: B. 4 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-27', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  27, '27', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'The presence of dust particles in air serves',
  '["As a nucleus to condense water vapour resulting in rain","To protect the inhabitants of the earth from the effects of ultra violet rays","To minimize the inflammatory nature of oxygen","To maintain the average density of air"]'::jsonb, 0, 'Correct option: A. As a nucleus to condense water vapour resulting in rain is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-28', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  28, '28', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'In the double displacement reaction between aqueous potassium iodide and aqueous lead nitrate, a yellow precipitate of lead iodide is formed. While performing the activity if lead nitrate is not available, which of the following can be used in place of lead nitrate?',
  '["Lead sulphate","Lead acetate","Ammonium nitrate","Potassium sulphate"]'::jsonb, 1, 'Correct option: B. Lead acetate is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-29', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  29, '29', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Formation of alkane by the action of Zn on alkyl halide is called',
  '["Frankland`s reaction","Wurtz`s reaction","Cannizzaro`s reactions","Kolbe`s reactions"]'::jsonb, 0, 'Correct option: A. Frankland`s reaction is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-30', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  30, '30', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'C10H22 + 900 K â†’ C4H8 + C6H14 Name the reaction',
  '["Elimination","Addition","Pyrolysis","Isomerisation"]'::jsonb, 2, 'Correct option: C. Pyrolysis is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-31', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  31, '31', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'In terms of acidic strength, which one of the following is in the correct increasing order',
  '["Water < Acetic acid < Hydrochloric acid","Water < Hydrochloric acid < Acetic acid","Acetic acid < Water < Hydrochloric acid","Hydrochloric acid < Water < Acetic acid"]'::jsonb, 0, 'Correct option: A. Water < Acetic acid < Hydrochloric acid is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-32', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  32, '32', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which of the following are exothermic processes? (i) Reaction of water with quick lime (ii) Dilution of an acid (iii) Evaporation of water (iv) Sublimation of camphor',
  '["(i) and (ii)","(ii) and (iii)","(i) and (iv)","(ii) and (iv)"]'::jsonb, 0, 'Correct option: A. (i) and (ii) is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-33', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  33, '33', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'How many isotopes have odd atomic number?',
  '["154","280","86","300"]'::jsonb, 2, 'Correct option: C. 86 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-34', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  34, '34', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'The major product formed by monobromination of methyl cyclopentane is',
  '["CH2Br","CH3 Br","CH3 Br Br","CH3Br"]'::jsonb, 3, 'Correct option: D. CH3Br is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-35', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  35, '35', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'The reducing power of a metal depends on various factors. Suggest the factor which makes Li, the strongest reducing agent in aqueous solution',
  '["Sublimation enthalpy","Ionisation enthalpy","Hydration enthalpy","Electron - gain enthalpy"]'::jsonb, 2, 'Correct option: C. Hydration enthalpy is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-36', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  36, '36', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Some of the group - 2 metal halides are covalent and soluble in organic solvents. Among the following metal halides, the one which is soluble in ethanol is',
  '["BeCl2","MgCl2","CaCl2","SrCl2"]'::jsonb, 0, 'Correct option: A. BeCl2 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-37', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  37, '37', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'When 0.5 mole of phosphoric acid is dissolved in aqueous solution how many moles of -ve and +ve ions are collected altogether?',
  '["0.5","1","1.5","2"]'::jsonb, 3, 'Correct option: D. 2 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-38', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  38, '38', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Lindlar''s Catalyst Na in Liq NH3 C CH3C CH3 A B In reaction A and B, respectively',
  '["cis and trans but-2- ene","trans and cis but-2- ene","Both cis but-2-ene","Both trans but-2-ene"]'::jsonb, 0, 'Correct option: A. cis and trans but-2- ene is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-39', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  39, '39', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Dead burnt plaster is',
  '["CaSO4","CaSO4.H2O","CaSO4.1/2H2O","CaSO4.H2O"]'::jsonb, 0, 'Correct option: A. CaSO4 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-40', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  40, '40', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'At 298 K temperature, if partial pressure of all given gases are same, then, which of the following gas possesses least solubility in water?',
  '["Carbon dioxide","Formaldehyde","Methane","Vinyl chloride"]'::jsonb, 2, 'Correct option: C. Methane is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-41', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  41, '41', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which of the following represents the given mode of hybridization sp2-sp2-sp-sp from left to right',
  '["CH H2C","CH CH","CH2 H2C","CH2 H2C"]'::jsonb, 0, 'Correct option: A. CH H2C is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-42', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  42, '42', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'When an electron is moving with velocity of 2.188 x 10^6 ms-1 in the first orbit of Bohrâ€™s model of hydrogen. The de Broglie wavelength of electron is',
  '["0.33 nm","0.34 nm","0.35 nm","0. 36 nm"]'::jsonb, 0, 'Correct option: A. 0.33 nm is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-43', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  43, '43', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Atomic number of Mn is 25. What is the electronic configuration in the ground state?',
  '["1s22s22p63s23p63d7","1s22s22p63s23p64s24p5","1s22s22p23s23p53d10","1s22s22p63s23p64s23d5"]'::jsonb, 3, 'Correct option: D. 1s22s22p63s23p64s23d5 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-44', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  44, '44', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'The balanced chemical equation for the reaction which occurs when Be is added to water is____________?',
  '["Be + 2H2O â†’ H2 + Be(OH)2","Be + H2O â†’ H2 + Be(OH)2","Be + H2O â†’ H2 + [Be (OH)4]","No reaction"]'::jsonb, 3, 'Correct option: D. No reaction is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-45', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  45, '45', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'A compound',
  '["on heating gives a colorless gas and a residue that is dissolved in water to obtain",". Excess of CO2 is bubbled through aqueous solution of B","is formed, which is recovered in the solid form. Solid (C) on gentle heating gives back (A). The compound is ... (a) CaCO3 (b) K2CO3 (c) Na2CO3","CaSO4.2H2O"]'::jsonb, 0, 'Correct option: A. on heating gives a colorless gas and a residue that is dissolved in water to obtain is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-46', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  46, '46', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Solubility of CaF2 is 2.0 x 10^-4 gdm-3 then Ksp of CaF2 is_______________?',
  '["4.0 x 10^-8","3.2 x 10^-11","2.0 x 10^-8","4.0 x 10^-12"]'::jsonb, 1, 'Correct option: B. 3.2 x 10^-11 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-47', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  47, '47', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Consider the following comparisons of Alkali Metals and Alkaline Earth Metals: 1 While no Alkali Metal is found free in nature, some alkaline earth metals are found free in nature 2 While alkali metals are highly reactive, alkaline earth metals are moderately reactive Which among the above statements is / are correct?',
  '["Only 1","Only 2","Both 1 & 2","Neither 1 nor 2"]'::jsonb, 1, 'Correct option: B. Only 2 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-48', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  48, '48', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which of the following alpha-emitter is commonly used in smoke detectors?',
  '["Bismuth-209","Amrecium-231","Uranium-238","Protactinium-231"]'::jsonb, 1, 'Correct option: B. Amrecium-231 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-49', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  49, '49', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which substance get oxidized in the reaction: 2Al + Cr2O3 â†’ Al2O3 + 2Cr',
  '["Al","Cr2O3","Al2O3","Cr"]'::jsonb, 0, 'Correct option: A. Al is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-50', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  50, '50', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'What is the oxidation no. of phosphorus in H3PO3, H3PO4, H3PO2 or phosphorus acid, phosphoric acid, phosphinic acid, respectively?',
  '["+3, +5, +1","+3, +5, +2","+4, +5, +1","+2, +5, +1"]'::jsonb, 0, 'Correct option: A. +3, +5, +1 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  6, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-51', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  51, '51', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'CH CH + O3 CH2 Cl2 196K X Zn/H2O Y End product Y is?',
  '["CH3CH2CH2COOH","CH3CH2CH2CHO","CH3OCCOCH3","OHCCHO"]'::jsonb, 3, 'Correct option: D. OHCCHO is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-52', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  52, '52', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'How many of the following metals when heated in an atmosphere of N2 gas form nitrides? Li, Na, K, Rb, Cs, Mg, Ca, Sr, Ba',
  '["9","5","3","6"]'::jsonb, 1, 'Correct option: B. 5 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-53', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  53, '53', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'If ionic substances completely dissociate, then aqueous solution of which of the following substances having least freezing point?',
  '["Glucose","NaCl","Al2(SO4)3","CaCl2"]'::jsonb, 2, 'Correct option: C. Al2(SO4)3 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-54', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  54, '54', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which type of solution, moist air is',
  '["Gas","Liquid","Solid","Colloidal"]'::jsonb, 0, 'Correct option: A. Gas is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-55', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  55, '55', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which of the following oxidation no. does not possess by nitrogen in any of its compound?',
  '["-1/3","-3","-4","+5"]'::jsonb, 2, 'Correct option: C. -4 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-56', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  56, '56', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which of the following is the component of most of the kidney stones',
  '["(COO)2Ca","(COONa)2","(COO)2 Ba","(COO)2Mg"]'::jsonb, 0, 'Correct option: A. (COO)2Ca is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-57', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  57, '57', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which substance is a reducing agent in the following reaction? Reaction : 2Al + Cr2O3 â†’ Al2O3 + 2Cr',
  '["Al","Cr2O3","Al2O3","Cr"]'::jsonb, 0, 'Correct option: A. Al is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-58', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  58, '58', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'What would be the formality of solution prepared by dissolving 9.48 g of Potash-alum in 5 L water? [M.W of Potash-alum = 948 g/mole]',
  '["0.04 F","0.02 F","0.002 F","0.004 F"]'::jsonb, 2, 'Correct option: C. 0.002 F is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-59', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  59, '59', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Radial nodes present in 3s and 2p-orbitals are respectively',
  '["0, 2","2, 0","2, 1","1, 2"]'::jsonb, 1, 'Correct option: B. 2, 0 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-60', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  60, '60', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', '30 g of Mg and 30 g of O2 are reacted and the residual mixure contains',
  '["60 g of MgO only","40 g of MgO and 20 g of O2","45 g of MgO and 15 g of O2","50 g of MgO and 10 g of O2"]'::jsonb, 3, 'Correct option: D. 50 g of MgO and 10 g of O2 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-61', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  61, '61', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'For a certain particle, it is found that uncertainty in velocity is reciprocal of uncertainty in position. This implies that',
  '["Mass of the particle is > unity","Mass of the particle is unity","Mass of the particle < h","Mass of the particle > h / 4pi"]'::jsonb, 3, 'Correct option: D. Mass of the particle > h / 4pi is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-62', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  62, '62', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'What would be the concentration in % w/v of aqueous solution in which 80 ml ethanol is dissolved in 4 L solution?',
  '["4% v/v","10% v/v","2% v/v","8% v/v"]'::jsonb, 2, 'Correct option: C. 2% v/v is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-63', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  63, '63', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'What will be final weight of 286 g Na2CO3 .10H2O by heating at 373 K',
  '["206 g","162 g","186 g","124 g"]'::jsonb, 3, 'Correct option: D. 124 g is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-64', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  64, '64', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Naphthalene is soluble in ether or benzene due to',
  '["Dipole-dipole attraction","Similar London forces","Hydrogen bond","Ionic attraction"]'::jsonb, 1, 'Correct option: B. Similar London forces is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-65', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  65, '65', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Which would undergo ð‘†ð‘ 2 reaction slow.',
  '["I","Cl","Br","a and b"]'::jsonb, 1, 'Correct option: B. Cl is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-66', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  66, '66', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'For nucleophilic substitution bimolecure ð‘†ð‘ 2 reaction give the correct order of reactivity.',
  '["2Â° halide < 3Â° halide < 1Â° halide","3Â° halide < 2Â° halide < 1Â° halide","3Â° halide < 2Â° halide > 1Â° halide","1Â° halide <3Â° halide 2Â° halide"]'::jsonb, 1, 'Correct option: B. 3Â° halide < 2Â° halide < 1Â° halide is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-67', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  67, '67', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'CH3 CH3H3C CH2OH gives which observation in Lucas test?',
  '["Reaction not take place","Give colour layer","Oilly point on layer","Milky solution"]'::jsonb, 0, 'Correct option: A. Reaction not take place is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-68', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  68, '68', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Splitting of spectral lines under the influence of magnetic field is called',
  '["Stark effect","Zeeman effect","Photoelectric effect","None of these"]'::jsonb, 1, 'Correct option: B. Zeeman effect is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  7, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-69', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  69, '69', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'For which compound iodoform test is not possible',
  '["C2H5OH","CH3CHO","COCH3","Benzophenone"]'::jsonb, 3, 'Correct option: D. Benzophenone is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-ii-70', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  70, '70', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'How many enantiomer pairs are obtained by monochlorination of 2, 3-dimethyl butane?',
  '["two","three","four","one"]'::jsonb, 3, 'Correct option: D. one is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  8, '', '{}'::jsonb
),
(
  'chemistry-2023-final-chemistry-2023-abc462e-part-iii-1', 'published', 'chemistry-2023-final-chemistry-2023-abc462e', 'Chemistry',
  71, 'Descriptive 1', 'Chemistry',
  'Descriptive', 'Descriptive', 'Long',
  'Part III', 'Descriptive Questions', 'NSTC',
  2023, 'NSTC 2023 Chemistry Paper', 'Chemistry-Descriptive Questions [Max points 30: All questions carry equal points] Question 1. What is the difference between a chemical process and a physical process in chemistry? Question 2. Explain with the help of examples that a geometrical isomerism is different from conformation. Question 3. Why propane is stored in household tanks but not natural gas? Question 4. How will you separate a mixture of o-nitrophenol and p-nitrophenol? -',
  '[]'::jsonb, null, 'A chemical process changes composition by breaking or forming bonds, while a physical process changes state, shape, or separation without changing molecular identity. Geometrical isomerism is a fixed cis/trans or E/Z arrangement caused by restricted rotation; conformations are interconvertible rotations around single bonds. Propane is stored in household tanks because it liquefies under moderate pressure, while methane-rich natural gas needs much higher pressure or cryogenic cooling. A mixture of o-nitrophenol and p-nitrophenol can be separated by steam distillation because the ortho isomer is more volatile due to intramolecular hydrogen bonding, whereas the para isomer forms intermolecular hydrogen bonds.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-1', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  1, '1', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'During cellular respiration breakdown of glucose occurs in',
  '["Vacuole","Golgi complex","Cytoplasm","Mitochondria"]'::jsonb, 3, 'Most aerobic breakdown of glucose occurs in mitochondria.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-2', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  2, '2', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'The following rays can cause cancer',
  '["X-rays","Gamma rays","Alpha and beta particles","All of these"]'::jsonb, 3, 'X-rays, gamma rays, alpha particles, and beta particles can all be ionizing cancer risks.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-3', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  3, '3', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'The hypothesis that stands the test of time are called',
  '["Law","Null Hypothesis","Principle","Theories"]'::jsonb, 3, 'Hypotheses that remain supported by repeated testing are called theories.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-4', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  4, '4', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'Electric intensity is a',
  '["vector","scalar","basic","none of these"]'::jsonb, 0, 'Electric field intensity has both magnitude and direction, so it is a vector.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-5', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  5, '5', 'Biology',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'One coulomb is equal to the charge of------------------------electrons.',
  '["6.25 x 10^19","6.24 x 10^18","6.24 x 10^17","6.25 x 10^18"]'::jsonb, 3, 'One coulomb is approximately the charge magnitude of 6.25 x 10^18 electrons.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-6', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  6, '6', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'The phenomenon of emission of light in a chemical reaction is known as',
  '["Chemiluminescence","Photosensitization","Luminescence","None of these"]'::jsonb, 0, 'Light emission during a chemical reaction is chemiluminescence.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-7', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  7, '7', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'Name the device used to measure the number of nuclear disintegration per minute',
  '["Cyclotron","Geiger counter","Cloud chamber","Mass spectrograph"]'::jsonb, 1, 'A Geiger counter measures counts from nuclear disintegrations.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-8', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  8, '8', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'Which of the following bonds must be present in alkynes?',
  '["Single bond","Double bond","triple bond","Hydrogen bond"]'::jsonb, 2, 'Alkynes contain at least one carbon-carbon triple bond.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-9', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  9, '9', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'When a solution contains equal concentration of hydroxyl and hydrogen ions its pH will be around',
  '["0","14","7","10"]'::jsonb, 2, 'Equal hydrogen and hydroxide ion concentrations make the solution neutral, around pH 7.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-10', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  10, '10', 'Chemistry',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'Which is the most reactive element in the given list?',
  '["Fluorine","Oxygen","Nitrogen","Iodine"]'::jsonb, 0, 'Fluorine is the most reactive element among the listed choices.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-11', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  11, '11', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'A quadrilateral with vertices at ( ) ( ) ( ) ( )0, â€“1 , 3,1 , 3, 1 , 0,1- is a __________.',
  '["kite","square","parallelogram","rectangle"]'::jsonb, 3, 'The listed vertices form a rectangle rather than a square or kite.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-12', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  12, '12', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'The center of the circle, __________.',
  '["is a point on the circle","lies outside of the circle","lies inside of the circle","none of these"]'::jsonb, 2, 'The center of a circle lies inside the circle, not on the circumference.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-13', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  13, '13', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'What is the sum of all the divisors of 600?',
  '["2060","1860","2160","1890"]'::jsonb, 1, '600=2^3*3*5^2, so the divisor sum is (1+2+4+8)(1+3)(1+5+25)=1860.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-14', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  14, '14', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'What is the sum of the first nine prime numbers?',
  '["100","98","80","77"]'::jsonb, 0, 'The first nine primes sum to 2+3+5+7+11+13+17+19+23=100.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-15', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  15, '15', 'Mathematics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'The equations 2x+7=3 and bx - 10 = -2 have the same solution. What is the value of b?',
  '["-4","6","2","3/ 2"]'::jsonb, 0, '2x+7=3 gives x=-2; substituting in bx-10=-2 gives b=-4.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-16', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  16, '16', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'A ball of mass m falls from rest onto a floor, from a height h. It makes elastic collisions with the floor repeatedly. The force exerted by it on the floor, averaged over a long time, is',
  '["mg","2 mg","3 mg","proportional to m and h"]'::jsonb, 0, 'Over a long time the average upward impulse from the floor balances the ball''s weight, so the average force is mg.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-17', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  17, '17', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'While passing over an obstacle a light ray slightly bends round the corner. The phenomenon is known as__',
  '["Scattering","Polarisation","Diffraction","Refraction"]'::jsonb, 2, 'Bending of light around an obstacle is diffraction.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-18', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  18, '18', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'What is the orbital velocity of geo stationary satellite?',
  '["4.15 km/s","2.78 km/s","3.08 km/s","6. 66 km/s"]'::jsonb, 2, 'A geostationary satellite moves at about 3.08 km/s in orbit.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-19', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  19, '19', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'What is the direction of electric and magnetic fields in an electromagnetic wave?',
  '["parallel to each other","at 90Â° to each other","at 45Â° to each other","at 120Â° to each other"]'::jsonb, 1, 'Electric and magnetic fields in an electromagnetic wave are perpendicular to each other.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-i-20', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  20, '20', 'Physics',
  'Common MCQ', 'Screening', 'MCQ',
  'Part I', 'Common MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'What is the time period of a seconds pendulum?',
  '["0.5 second","1.0 seconds","1.5 seconds","2.0 seconds"]'::jsonb, 3, 'A seconds pendulum has a time period of 2.0 seconds.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-ii-21', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  21, '21', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'How many orbitals are in an atomic sublevel with l = 3?',
  '["3","5","7","9"]'::jsonb, 2, 'Correct option: C. 7 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-ii-22', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  22, '22', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'A ground state gaseous atom of which element has the greatest number of unpaired electrons?',
  '["As","Br","Ge","Se"]'::jsonb, 0, 'Correct option: A. As is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-ii-23', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  23, '23', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'An atom of which element has the highest second ionization energy?',
  '["Na","Mg","Al","K"]'::jsonb, 0, 'Correct option: A. Na is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-ii-24', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  24, '24', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'For the elements in group 14 (C to Pb), which property increases with increasing atomic number?',
  '["melting points","covalent radius","magnitude of stable oxidation state","ability to form chains of atoms with themselves"]'::jsonb, 1, 'Correct option: B. covalent radius is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-ii-25', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  25, '25', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'When NaF, MgO, KCl and CaS are listed in order of increasing lattice energy, which order is correct?',
  '["MgO, NaF, KCl, CaS","CaS, MgO, KCl, NaF","KCl, CaS, NaF, MgO","KCl, NaF, CaS, MgO"]'::jsonb, 3, 'Correct option: D. KCl, NaF, CaS, MgO is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-ii-26', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  26, '26', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'A mineral containing only manganese and oxygen contains 69.6% Mn by mass. What is its empirical formula?',
  '["MnO","Mn2O3","Mn3O4","MnO2"]'::jsonb, 1, 'Correct option: B. Mn2O3 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-ii-27', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  27, '27', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'Toluene, C7H8, is added to gasoline to increase its octane rating. What is the volume ratio of air to toluene vapor to burn completely to form CO2 and H2O? (Assume air is 20% O2 by volume.)',
  '["9/1","11/1","28/1","45/1"]'::jsonb, 3, 'Correct option: D. 45/1 is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-ii-28', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  28, '28', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'Which of the following acids does not commonly form acidic salts?',
  '["HCl","H2SO4","H2CO3","H3PO4"]'::jsonb, 0, 'Correct option: A. HCl is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
),
(
  'chemistry-2024-final-chemistry-2024-1800740-part-ii-29', 'published', 'chemistry-2024-final-chemistry-2024-1800740', 'Chemistry',
  29, '29', 'Chemistry',
  'Chemistry MCQ', 'Subject MCQ', 'MCQ',
  'Part II', 'Chemistry MCQs', 'NSTC',
  2024, 'NSTC 2024 Chemistry Paper', 'Which of the following reactions can not be used to form salts?',
  '["The reaction between a non- metal and oxygen","The reaction between a metal oxide and an acid","The reaction between an acid and a base","The reaction between an acid anhydride and metal oxide"]'::jsonb, 0, 'Correct option: A. The reaction between a non- metal and oxygen is the verified choice from the source paper; it follows from the standard chemistry result needed by the prompt.',
  null, '', '{}'::jsonb
)
on conflict (id) do update set
  status = excluded.status,
  paper_id = excluded.paper_id,
  paper_subject = excluded.paper_subject,
  number = excluded.number,
  display_number = excluded.display_number,
  subject = excluded.subject,
  topic = excluded.topic,
  difficulty = excluded.difficulty,
  type = excluded.type,
  section = excluded.section,
  section_title = excluded.section_title,
  exam = excluded.exam,
  year = excluded.year,
  source = excluded.source,
  prompt = excluded.prompt,
  options = excluded.options,
  answer = excluded.answer,
  solution = excluded.solution,
  page = excluded.page,
  figure = excluded.figure,
  metadata = excluded.metadata;

commit;
