import {
  Activity,
  Atom,
  BookOpen,
  BookOpenCheck,
  Bookmark,
  Calculator,
  CalendarDays,
  Check,
  ChevronRight,
  ClipboardCheck,
  ClipboardList,
  Code2,
  Dna,
  Download,
  Eye,
  FileText,
  Flag,
  FlaskConical,
  GraduationCap,
  LayoutDashboard,
  Lightbulb,
  ListChecks,
  Medal,
  MoonStar,
  Orbit,
  Pause,
  PenLine,
  Pi,
  Rocket,
  Route,
  Search,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  Tent,
  Timer,
  Trophy,
  Users,
  Waves,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  activity: Activity,
  atom: Atom,
  "book-open": BookOpen,
  book: BookOpenCheck,
  bookmark: Bookmark,
  calculator: Calculator,
  calendar: CalendarDays,
  check: Check,
  chevron: ChevronRight,
  "clipboard-check": ClipboardCheck,
  clipboard: ClipboardList,
  code: Code2,
  dna: Dna,
  download: Download,
  eye: Eye,
  "file-text": FileText,
  flag: Flag,
  flask: FlaskConical,
  "graduation-cap": GraduationCap,
  dashboard: LayoutDashboard,
  lightbulb: Lightbulb,
  "list-checks": ListChecks,
  medal: Medal,
  moonstar: MoonStar,
  orbit: Orbit,
  pause: Pause,
  pen: PenLine,
  pi: Pi,
  rocket: Rocket,
  route: Route,
  running: Activity,
  search: Search,
  shield: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  tent: Tent,
  timer: Timer,
  trophy: Trophy,
  users: Users,
  waves: Waves,
};

export function Icon({
  name,
  className,
  strokeWidth = 1.8,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Component = icons[name] ?? Sparkles;
  return <Component aria-hidden className={className} strokeWidth={strokeWidth} />;
}
