import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { alumniStories, blogPosts } from "../src/lib/data";
import { getAllGuides } from "../src/lib/guides";
import { resources as normalizedResources } from "../src/lib/content-data";

type JsonObject = Record<string, unknown>;

type ResourceSeed = {
  id: string;
  title: string;
  description?: string;
  subject: string;
  kind: string;
  folder?: string;
  year?: number | null;
  pages?: number | null;
  sizeBytes?: number | null;
  localUrl?: string | null;
  sourceUrl?: string | null;
};

type PastPaperSeed = {
  id: string;
  title: string;
  exam: string;
  subject: string;
  year: number;
  pages?: number | null;
  resourceUrl?: string | null;
  sourceUrl?: string | null;
  scanned?: boolean | null;
  pageImages?: string[] | null;
  questionCount?: number | null;
  mcqCount?: number | null;
  descriptiveCount?: number | null;
  partICount?: number | null;
  partIICount?: number | null;
};

type QuestionSeed = {
  id: string;
  paperId?: string | null;
  paperSubject?: string | null;
  number: number;
  displayNumber?: string | null;
  subject: string;
  topic?: string | null;
  difficulty?: string | null;
  type: string;
  section?: string | null;
  sectionTitle?: string | null;
  exam?: string | null;
  year?: number | null;
  source?: string | null;
  prompt: string;
  options?: unknown[] | null;
  answer?: number | null;
  solution?: string | null;
  page?: number | null;
  figure?: string | null;
};

type ContentSeed = {
  kind: "blog_post" | "guide" | "alumni_story";
  slug: string;
  title: string;
  excerpt: string;
  body: string;
  category: string;
  authorName: string;
  readTime: string;
  sourceUrl?: string;
  videoUrl?: string;
  videoId?: string;
  videoTitle?: string;
  featured?: boolean;
  metadata: JsonObject;
  publishedAt: string;
};

const root = path.resolve(__dirname, "..");
const outDir = path.join(root, "supabase", "seeds");
const unsafeControlChars = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g;

function readJson<T>(relativePath: string): T {
  return JSON.parse(fs.readFileSync(path.join(root, relativePath), "utf8")) as T;
}

function cleanSeedText(value: string) {
  return value.replace(unsafeControlChars, " ");
}

function cleanJsonValue(value: unknown): unknown {
  if (typeof value === "string") return cleanSeedText(value);
  if (Array.isArray(value)) return value.map((item) => cleanJsonValue(item));
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, cleanJsonValue(item)]));
  }
  return value;
}

function sqlString(value: string | null | undefined) {
  if (value === null || value === undefined) return "null";
  return `'${cleanSeedText(value).replace(/'/g, "''")}'`;
}

function sqlRequiredString(value: string | null | undefined, fallback = "") {
  return sqlString(value ?? fallback);
}

function sqlNonEmptyString(value: string | null | undefined) {
  return value && value.trim() ? sqlString(value) : "null";
}

function sqlNumber(value: number | null | undefined) {
  return typeof value === "number" && Number.isFinite(value) ? String(value) : "null";
}

function sqlBoolean(value: boolean | null | undefined) {
  return value ? "true" : "false";
}

function sqlJson(value: unknown, fallback: unknown) {
  return `${sqlString(JSON.stringify(cleanJsonValue(value ?? fallback)))}::jsonb`;
}

function sqlTextArray(value: string[] | null | undefined) {
  const items = Array.isArray(value) ? value : [];
  return `array[${items.map((item) => sqlString(item)).join(", ")}]::text[]`;
}

function sqlTimestamp(value: string) {
  return `${sqlString(value)}::timestamptz`;
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

function readMinutes(body: string) {
  const words = body.trim().split(/\s+/).filter(Boolean).length;
  return `${Math.max(1, Math.ceil(words / 220))} min`;
}

function parseDate(value: string) {
  const parsed = Date.parse(value);
  return Number.isNaN(parsed) ? new Date().toISOString() : new Date(parsed).toISOString();
}

function deterministicUuid(key: string) {
  const bytes = createHash("sha1").update(key).digest().subarray(0, 16);
  bytes[6] = (bytes[6] & 0x0f) | 0x50;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = bytes.toString("hex");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

function sqlHeader(title: string) {
  return [
    `-- ${title}`,
    "-- Generated by scripts/generate_supabase_seed_sql.ts.",
    "-- Run the schema migration first, then run these seed files in filename order.",
    "",
  ].join("\n");
}

function writeSqlFile(name: string, sql: string) {
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, name), `${sql.trim()}\n`, "utf8");
}

function contentSeeds(): ContentSeed[] {
  const posts = blogPosts.map((post) => ({
    kind: "blog_post" as const,
    slug: post.slug,
    title: post.title,
    excerpt: post.excerpt,
    body: post.content,
    category: post.category,
    authorName: post.author,
    readTime: post.read,
    videoUrl: post.videoUrl,
    videoId: post.videoId,
    videoTitle: post.videoTitle,
    metadata: {
      legacyDate: post.date,
      tags: [post.category],
    },
    publishedAt: parseDate(post.date),
  }));

  const guides = getAllGuides().map((guide) => ({
    kind: "guide" as const,
    slug: guide.slug,
    title: guide.title,
    excerpt: guide.description,
    body: guide.content,
    category: guide.category,
    authorName: guide.author,
    readTime: guide.readTime || readMinutes(guide.content),
    sourceUrl: guide.sourceUrl,
    featured: guide.featured,
    metadata: {
      level: guide.level,
      tags: guide.tags,
      updated: guide.updated,
    },
    publishedAt: parseDate(guide.updated),
  }));

  const alumni = alumniStories.map((story) => ({
    kind: "alumni_story" as const,
    slug: slugify(story.name),
    title: story.name,
    excerpt: story.quote,
    body: story.quote,
    category: story.subject,
    authorName: "Pakistan Olympiads",
    readTime: "2 min",
    metadata: {
      achievement: story.achievement,
      subject: story.subject,
      location: story.location,
      role: story.role,
      tags: [story.subject, "Alumni"],
    },
    publishedAt: new Date().toISOString(),
  }));

  return [...posts, ...guides, ...alumni];
}

function contentSql(seeds: ContentSeed[]) {
  const statements: string[] = [sqlHeader("Content seed: blog posts, guides, revisions, and tags"), "begin;"];

  for (const item of seeds) {
    const contentId = deterministicUuid(`content:${item.kind}:${item.slug}`);
    const tags = Array.isArray(item.metadata.tags) ? item.metadata.tags.filter((tag): tag is string => typeof tag === "string") : [];

    statements.push(`
insert into public.content_items (
  id, kind, status, slug, title, excerpt, body, category, author_name, read_time,
  source_url, video_url, video_id, video_title, featured, metadata, published_at
) values (
  ${sqlString(contentId)}, ${sqlString(item.kind)}, 'published', ${sqlString(item.slug)}, ${sqlString(item.title)},
  ${sqlString(item.excerpt)}, ${sqlString(item.body)}, ${sqlString(item.category)}, ${sqlString(item.authorName)},
  ${sqlString(item.readTime)}, ${sqlRequiredString(item.sourceUrl)}, ${sqlRequiredString(item.videoUrl)},
  ${sqlRequiredString(item.videoId)}, ${sqlRequiredString(item.videoTitle)}, ${sqlBoolean(item.featured)},
  ${sqlJson(item.metadata, {})}, ${sqlTimestamp(item.publishedAt)}
)
on conflict (kind, slug) do update set
  status = excluded.status,
  title = excluded.title,
  excerpt = excluded.excerpt,
  body = excluded.body,
  category = excluded.category,
  author_name = excluded.author_name,
  read_time = excluded.read_time,
  source_url = excluded.source_url,
  video_url = excluded.video_url,
  video_id = excluded.video_id,
  video_title = excluded.video_title,
  featured = excluded.featured,
  metadata = excluded.metadata,
  published_at = excluded.published_at;`);

    statements.push(`
insert into public.content_revisions (
  content_id, revision_number, title, excerpt, body, metadata, status
)
select
  id, 1, ${sqlString(item.title)}, ${sqlString(item.excerpt)}, ${sqlString(item.body)},
  ${sqlJson(item.metadata, {})}, 'published'
from public.content_items
where kind = ${sqlString(item.kind)}
  and slug = ${sqlString(item.slug)}
on conflict (content_id, revision_number) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  body = excluded.body,
  metadata = excluded.metadata,
  status = excluded.status;`);

    for (const tag of tags) {
      const tagSlug = slugify(tag);
      const tagId = deterministicUuid(`tag:${tagSlug}`);
      statements.push(`
insert into public.tags (id, slug, label)
values (${sqlString(tagId)}, ${sqlString(tagSlug)}, ${sqlString(tag)})
on conflict (slug) do update set label = excluded.label;

insert into public.content_tags (content_id, tag_id)
select content_items.id, tags.id
from public.content_items
cross join public.tags
where content_items.kind = ${sqlString(item.kind)}
  and content_items.slug = ${sqlString(item.slug)}
  and tags.slug = ${sqlString(tagSlug)}
on conflict do nothing;`);
    }
  }

  statements.push("commit;");
  return statements.join("\n");
}

function resourcesSql(resources: ResourceSeed[]) {
  const values = resources.map((resource) => `(
  ${sqlString(resource.id)}, 'published', ${sqlString(resource.title)}, ${sqlRequiredString(resource.description)},
  ${sqlString(resource.subject)}, ${sqlString(resource.kind)}, ${sqlRequiredString(resource.folder)},
  ${sqlNumber(resource.year)}, ${sqlNumber(resource.pages ?? 0)}, ${sqlNumber(resource.sizeBytes ?? 0)},
  ${sqlString(resource.localUrl)}, ${sqlRequiredString(resource.sourceUrl)}, '{}'::jsonb
)`);

  return `${sqlHeader("Resource seed")}
begin;

insert into public.resources (
  id, status, title, description, subject, kind, folder, year, pages,
  size_bytes, local_url, source_url, metadata
) values
${values.join(",\n")}
on conflict (id) do update set
  status = excluded.status,
  title = excluded.title,
  description = excluded.description,
  subject = excluded.subject,
  kind = excluded.kind,
  folder = excluded.folder,
  year = excluded.year,
  pages = excluded.pages,
  size_bytes = excluded.size_bytes,
  local_url = excluded.local_url,
  source_url = excluded.source_url,
  metadata = excluded.metadata;

commit;`;
}

function pastPapersSql(papers: PastPaperSeed[]) {
  const values = papers.map((paper) => `(
  ${sqlString(paper.id)}, 'published', ${sqlString(paper.title)}, ${sqlString(paper.exam)}, ${sqlString(paper.subject)},
  ${sqlNumber(paper.year)}, ${sqlNumber(paper.pages ?? 0)}, ${sqlString(paper.resourceUrl)},
  ${sqlRequiredString(paper.sourceUrl)}, ${sqlBoolean(paper.scanned)}, ${sqlTextArray(paper.pageImages)},
  ${sqlNumber(paper.questionCount ?? 0)}, ${sqlNumber(paper.mcqCount ?? 0)}, ${sqlNumber(paper.descriptiveCount ?? 0)},
  ${sqlNumber(paper.partICount ?? 0)}, ${sqlNumber(paper.partIICount ?? 0)}, '{}'::jsonb
)`);

  return `${sqlHeader("Past paper seed")}
begin;

insert into public.past_papers (
  id, status, title, exam, subject, year, pages, resource_url, source_url, scanned,
  page_images, question_count, mcq_count, descriptive_count, part_i_count, part_ii_count, metadata
) values
${values.join(",\n")}
on conflict (id) do update set
  status = excluded.status,
  title = excluded.title,
  exam = excluded.exam,
  subject = excluded.subject,
  year = excluded.year,
  pages = excluded.pages,
  resource_url = excluded.resource_url,
  source_url = excluded.source_url,
  scanned = excluded.scanned,
  page_images = excluded.page_images,
  question_count = excluded.question_count,
  mcq_count = excluded.mcq_count,
  descriptive_count = excluded.descriptive_count,
  part_i_count = excluded.part_i_count,
  part_ii_count = excluded.part_ii_count,
  metadata = excluded.metadata;

commit;`;
}

function questionsSql(questions: QuestionSeed[], chunkNumber: number) {
  const values = questions.map((question) => `(
  ${sqlString(question.id)}, 'published', ${sqlNonEmptyString(question.paperId)}, ${sqlRequiredString(question.paperSubject)},
  ${sqlNumber(question.number)}, ${sqlRequiredString(question.displayNumber)}, ${sqlString(question.subject)},
  ${sqlRequiredString(question.topic)}, ${sqlRequiredString(question.difficulty)}, ${sqlString(question.type)},
  ${sqlRequiredString(question.section)}, ${sqlRequiredString(question.sectionTitle)}, ${sqlRequiredString(question.exam)},
  ${sqlNumber(question.year)}, ${sqlRequiredString(question.source)}, ${sqlString(question.prompt)},
  ${sqlJson(question.options, [])}, ${sqlNumber(question.answer)}, ${sqlRequiredString(question.solution)},
  ${sqlNumber(question.page)}, ${sqlRequiredString(question.figure)}, '{}'::jsonb
)`);

  return `${sqlHeader(`Question seed chunk ${chunkNumber}`)}
begin;

insert into public.questions (
  id, status, paper_id, paper_subject, number, display_number, subject, topic,
  difficulty, type, section, section_title, exam, year, source, prompt,
  options, answer, solution, page, figure, metadata
) values
${values.join(",\n")}
on conflict (id) do update set
  status = excluded.status,
  paper_id = excluded.paper_id,
  paper_subject = excluded.paper_subject,
  number = excluded.number,
  display_number = excluded.display_number,
  subject = excluded.subject,
  topic = excluded.topic,
  difficulty = excluded.difficulty,
  type = excluded.type,
  section = excluded.section,
  section_title = excluded.section_title,
  exam = excluded.exam,
  year = excluded.year,
  source = excluded.source,
  prompt = excluded.prompt,
  options = excluded.options,
  answer = excluded.answer,
  solution = excluded.solution,
  page = excluded.page,
  figure = excluded.figure,
  metadata = excluded.metadata;

commit;`;
}

function removeOldSeedFiles() {
  if (!fs.existsSync(outDir)) return;
  for (const file of fs.readdirSync(outDir)) {
    if (/^\d{3}_.*\.sql$/.test(file)) {
      fs.unlinkSync(path.join(outDir, file));
    }
  }
}

function main() {
  const papers = readJson<PastPaperSeed[]>("src/data/past-papers.json");
  const questions = readJson<QuestionSeed[]>("src/data/questions.json");
  const allContent = contentSeeds();
  const questionChunkSize = 150;

  removeOldSeedFiles();
  writeSqlFile("001_content.sql", contentSql(allContent));
  writeSqlFile("002_resources.sql", resourcesSql(normalizedResources));
  writeSqlFile("003_past_papers.sql", pastPapersSql(papers));

  for (let index = 0; index < questions.length; index += questionChunkSize) {
    const chunk = questions.slice(index, index + questionChunkSize);
    const chunkNumber = Math.floor(index / questionChunkSize) + 1;
    writeSqlFile(`004_questions_${String(chunkNumber).padStart(3, "0")}.sql`, questionsSql(chunk, chunkNumber));
  }

  console.log(`Generated SQL seed files in ${path.relative(root, outDir)}:`);
  console.log(`- ${allContent.length} content items`);
  console.log(`- ${normalizedResources.length} resources`);
  console.log(`- ${papers.length} past papers`);
  console.log(`- ${questions.length} questions split into ${Math.ceil(questions.length / questionChunkSize)} chunks`);
}

main();
